# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-scraper/api

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-scraper-service/logs/emdb-scraper-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."io.quarkus".handlers=LOG_FILE
quarkus.log.category."io.smallrye".level=WARN
quarkus.log.category."io.smallrye".handlers=LOG_FILE
quarkus.log.category."org.apache.kafka.clients.producer".level=WARN
quarkus.log.category."org.apache.kafka.clients.producer".min-level=TRACE
quarkus.log.category."org.apache.kafka.clients.producer".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.scraper".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.scraper".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=DEBUG
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE

# --------------------------------------------------------------------
# --- DEVELOPMENT TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=3
tmdb.crew.limit=2
tmdb.rate.limit=5000

