# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/api/v1
quarkus.http.port=60314

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.ingest-commands.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-commands.exchange.name=emdb.ingest.commands
mp.messaging.incoming.ingest-commands.exchange.type=direct
mp.messaging.incoming.ingest-commands.queue.name=emdb-ingest.ingest-media
mp.messaging.incoming.ingest-commands.routing-keys=ingest.media
mp.messaging.incoming.ingest-commands.max-outstanding-messages=1
mp.messaging.incoming.ingest-commands.queue.single-active-consumer=true
