# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/api/v1
quarkus.http.port=60314

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.ingest-media.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-media.exchange.name=emdb.ingest.commands
mp.messaging.incoming.ingest-media.exchange.type=direct
mp.messaging.incoming.ingest-media.queue.name=emdb-ingest.ingest-media
mp.messaging.incoming.ingest-media.routing-keys=ingest.media
mp.messaging.incoming.ingest-media.max-outstanding-messages=1
mp.messaging.incoming.ingest-media.queue.single-active-consumer=true

mp.messaging.outgoing.ingest-events.connector=smallrye-kafka
mp.messaging.outgoing.ingest-events.topic=emdb.ingest.events
mp.messaging.outgoing.ingest-events.key.serializer=org.apache.kafka.common.serialization.UUIDSerializer
mp.messaging.outgoing.ingest-events.acks=all

mp.messaging.outgoing.extract-movies.connector=smallrye-kafka
mp.messaging.outgoing.extract-movies.topic=emdb.extract.movies
mp.messaging.outgoing.extract-movies.key.serializer=org.apache.kafka.common.serialization.IntegerSerializer
mp.messaging.outgoing.extract-movies.acks=all
