# --------------------------------------------------------------------
# --- ALL PROFILES
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60314
quarkus.index-dependency.web-services.group-id=com.erdouglass
quarkus.index-dependency.web-services.artifact-id=web-services

# --------------------------------------------------------------------
# --- DEFAULT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.console.level=INFO
quarkus.log.category."io.smallrye.reactive.messaging.rabbitmq".level=ERROR

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.movie-ingest-in.connector=smallrye-rabbitmq
mp.messaging.incoming.movie-ingest-in.exchange.name=emdb-exchange
mp.messaging.incoming.movie-ingest-in.exchange.type=topic
mp.messaging.incoming.movie-ingest-in.routing-keys=movie.ingest
mp.messaging.incoming.movie-ingest-in.queue.name=movie-ingest
mp.messaging.incoming.movie-ingest-in.prefetch=1

mp.messaging.outgoing.movie-create-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.movie-create-out.exchange.name=emdb-exchange
mp.messaging.outgoing.movie-create-out.exchange.type=topic
mp.messaging.outgoing.movie-create-out.routing-key=movie.create

# --------------------------------------------------------------------
# --- DEFAULT TMDB CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbMovieClient".url=https://api.themoviedb.org/3
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbPersonClient".url=https://api.themoviedb.org/3
