package com.erdouglass.emdb.media.entity;

import java.time.Instant;
import java.util.Objects;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotNull;

/// A base class for all persistent entities in the application.
///
/// As a `@MappedSuperclass`, this class is not an entity itself, but provides
/// common, non-domain-specific fields to all concrete entity subclasses.
///
/// ## Key Features
///
/// * **`id`**: A surrogate primary key, auto-generated by a sequence.
/// * **`tmdbId`**: A generic, unique business key (e.g., the ID from TMDB).
///     This is used for all `equals()` and `hashCode()` comparisons, which is
///     a best practice for JPA entities to ensure consistent behavior
///     across different persistence states.
/// * **Timestamps**: `created` and `modified` fields are automatically managed
///     by Hibernate's `@CreationTimestamp` and `@UpdateTimestamp`.
///
/// @param <T> The type of the `tmdbId` (e.g., `Integer` for shows, `String` for people).
@MappedSuperclass
public abstract class BasicEntity<T> {
  public static final String SEQUENCE_GENERATOR = "sequence_generator";

  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant created;

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;

  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modified;
  
	@NotNull
	@Column(name = "tmdb_id", unique = true, updatable = false)
	private T tmdbId;

  protected BasicEntity() {
  	
  }
  
  protected BasicEntity(T tmdbId) {
  	this.tmdbId = tmdbId;
  }

  public Instant created() {
    return created;
  }

  public void id(Long id) {
    this.id = id;
  }

  public Long id() {
    return id;
  }

  public Instant modified() {
    return modified;
  }
  
  public T tmdbId() {
  	return tmdbId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicEntity<?> other = (BasicEntity<?>) o;
    return Objects.equals(tmdbId, other.tmdbId);
  }
  
  @Override
  public int hashCode() {
    return Objects.hash(tmdbId);
  }
  
}
