package com.erdouglass.emdb.media.entity;

import java.time.Instant;
import java.util.Objects;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.erdouglass.emdb.common.configuration.Configuration;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/// A base abstract class for all entities requiring a primary key,
/// business key (`source` + `externalId`), and auditing timestamps.
///
/// Equality is determined by the natural business key
/// ({@code source} and {@code externalId}), not the surrogate
/// primary key ({@code id}).
///
/// @param <T> The data type of the external identifier (e.g., {@code Long}
///            for TMDB, {@code String} for IMDB).
@MappedSuperclass
public abstract class BasicEntity<T> {
  public static final String SEQUENCE_GENERATOR = "sequence_generator";

  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant created;
  
  /// The unique identifier from an external data source (e.g., TMDB ID).
  /// This field is part of the natural business key and cannot be updated.
	@NotNull
	@Column(name = "external_id", updatable = false)
	private T externalId;

	/// The surrogate primary key for the entity, generated by a sequence.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;

  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modified;
  
  /// The name of the data source (e.g., "tmdb", "trakt").
  /// This field is part of the natural business key and cannot be updated.
  @NotBlank 
  @Size(max = Configuration.SOURCE_MAX_LENGTH)
  @Column(updatable = false)
  private String source;

  /// Default protected constructor for JPA and proxying.
  protected BasicEntity() {
  	
  }
  
  /// Creates a new entity with its external (business) ID.
  ///
  /// @param source The source of the external identifier
  /// @param externalId The external identifier.
  protected BasicEntity(String source, T externalId) {
  	this.source = source;
  	this.externalId = externalId;
  }

  public Instant created() {
    return created;
  }
  
  public T externalId() {
  	return externalId;
  }

  public void id(Long id) {
    this.id = id;
  }

  public Long id() {
    return id;
  }

  public Instant modified() {
    return modified;
  }
  
  public String source() {
  	return source;
  }

  /// Compares this entity to another object for equality.
  ///
  /// This implementation uses the natural business key
  /// ({@code source} and {@code externalId}) rather than the
  /// surrogate {@code id}. This allows for comparison of
  /// transient (unsaved) entities.
  ///
  /// It is proxy-safe, using {@code instanceof} instead of
  /// {@code getClass() != o.getClass()}.
  ///
  /// @param o The object to compare with.
  /// @return {@code true} if the objects are equal based on
  ///         business key, {@code false} otherwise.
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || !(o instanceof BasicEntity)) {
      return false;
    }
    BasicEntity<?> other = (BasicEntity<?>) o;
    return Objects.equals(source, other.source)
    		&& Objects.equals(externalId, other.externalId);
  }
  
  /// Generates a hash code based on the natural business key
  /// ({@code source} and {@code externalId}).
  ///
  /// This is consistent with the {@link #equals(Object)}
  /// implementation.
  ///
  /// @return The hash code.
  @Override
  public int hashCode() {
    return Objects.hash(source, externalId);
  }
  
}
