package com.erdouglass.emdb.media.entity;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.uuid.Generators;
import com.fasterxml.uuid.impl.TimeBasedEpochGenerator;

/// Base class for all JPA entities in the application, providing common
/// auditing and identity management.
///
/// This class implements a highly robust identity strategy. It uses a
/// database-generated sequential ID for optimal index performance, combined with
/// an immutable, time-based UUIDv7 (`uid`) generated at instantiation. This
/// ensures entities can be safely placed in `HashSet`s prior to persistence
/// without degrading database insert performance via index fragmentatition.
@MappedSuperclass
public abstract class SequenceEntity {
  public static final String SEQUENCE_GENERATOR = "sequence_generator";
  private static final TimeBasedEpochGenerator UID_GENERATOR = Generators.timeBasedEpochGenerator();

  /// The timestamp when this entity was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant created;

  /// The primary key is generated by a database sequence that is intentionally 
  /// exposed to the public giving it business meaning. This is URL friendly and
  /// makes it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;

  /// The timestamp when this entity was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modified;

  @Column(nullable = false, updatable = false, unique = true)
  private final UUID uid = UID_GENERATOR.generate();

  /// Default protected constructor for JPA and proxying.
  protected SequenceEntity() {

  }

  public Instant getCreated() {
    return created;
  }

  public Long getId() {
    return id;
  }

  public Instant getModified() {
    return modified;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof SequenceEntity other))
      return false;
    return uid != null && uid.equals(other.uid);
  }

  @Override
  public int hashCode() {
    return uid.hashCode();
  }
}
