package com.erdouglass.emdb.media.entity;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import com.fasterxml.uuid.Generators;

@MappedSuperclass
public abstract class UuidEntity {
  
  /// The timestamp when this entity was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant created;
  
  /// The primary key is generated by the database using [UuidGenerator.Style.TIME]
  /// strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  /// The timestamp when this entity was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modified;
  
  /// The uid provides a stable unique id for Java identity.
  @Column(nullable = false, updatable = false, unique = true)
  private final UUID uid = Generators.timeBasedEpochGenerator().generate();
  
  protected UuidEntity() {
    
  }
  
  public Instant getCreated() {
    return created;
  }

  public UUID getId() {
    return id;
  }

  public Instant getModified() {
    return modified;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o)
      return true;
    if (!(o instanceof UuidEntity other))
      return false;
    return uid != null && uid.equals(other.uid);
  }

  @Override
  public int hashCode() {
    return uid.hashCode();
  }

}
