package com.erdouglass.emdb.job.entity;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import com.erdouglass.emdb.common.MediaType;
import com.erdouglass.emdb.common.ShowConstants;
import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestSource;
import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestStatus;

@Entity
@Table(name = "Ingest_Jobs")
public class IngestJob {
  
  @Positive
  @Column(name = "emdb_id")
  private Long emdbId;
  
  /// The primary key is generated by the application.
  @Id
  private UUID id;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestSource source;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestStatus status;
  
  @NotNull
  private Instant timestamp;
  
  /// The title of a show or name of a person.
  @Size(max = ShowConstants.TITLE_MAX_LENGTH)
  private String name;
  
  @NotNull
  @Positive
  @Column(name = "tmdb_id")
  private Integer tmdbId;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private MediaType type;
  
  public IngestJob() {
    
  }
  
  public void emdbId(Long emdbId) {
    this.emdbId = emdbId;
  }
  
  public Optional<Long> emdbId() {
    return Optional.ofNullable(emdbId);
  }
  
  public void id(UUID id) {
    this.id = id;
  }
  
  public UUID id() {
    return id;
  }
  
  public void name(String name) {
    this.name = name;
  }

  public Optional<String> name() {
    return Optional.ofNullable(name);
  }
  
  public void source(IngestSource source) {
    this.source = source;
  }
  
  public IngestSource source() {
    return source;
  }
  
  public void status(IngestStatus status) {
    this.status = status;
  }
  
  public IngestStatus status() {
    return status;
  }
  
  public void timestamp(Instant timestamp) {
    this.timestamp = timestamp;
  }
  
  public Instant timestamp() {
    return timestamp;
  }
  
  public void tmdbId(Integer tmdbId) {
    this.tmdbId = tmdbId;
  }
  
  public Integer tmdbId() {
    return tmdbId;
  }
  
  public void type(MediaType type) {
    this.type = type;
  }
  
  public MediaType type() {
    return type;
  }
  
  @Override
  public String toString() {
    return "IngestJob[id=" + id
        + ", emdbId=" + emdbId
        + ", tmdbId=" + tmdbId
        + ", timestamp=" + timestamp
        + ", source=" + source
        + ", type=" + type
        + ", status=" + status
        + "]";
  }

}
