package com.erdouglass.emdb.job.entity;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import com.erdouglass.emdb.common.message.JobMessage.JobSource;
import com.erdouglass.emdb.common.message.JobMessage.JobStatus;

@Entity
@Table(name = "Job_History")
public class JobLog {
  private static final String SEQUENCE_GENERATOR = "sequence_generator";

  /// The surrogate primary key is generated by the database and has no 
  /// business meaning.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  @SequenceGenerator(
      name = SEQUENCE_GENERATOR, 
      sequenceName = "job_sequence", 
      initialValue = 1)
  private Long id;
  
  @NotBlank
  private String content;
  
  @NotBlank 
  @Column(name = "job_id")
  private String jobId;
  
  @NotNull 
  @Min(0) @Max(100)
  private Integer progress;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private JobSource source;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private JobStatus status;
  
  @NotNull
  private Instant timestamp;
  
  JobLog() {
    
  }
  
  public void content(String content) {
    this.content = content;
  }
  
  public String content() {
    return content;
  }
  
  public JobLog(String jobId) {
    this.jobId = jobId;
  }
  
  public String jobId() {
    return jobId;
  }
  
  public void progress(Integer progress) {
    this.progress = progress;
  }
  
  public Integer progress() {
    return progress;
  }
  
  public void source(JobSource source) {
    this.source = source;
  }
  
  public JobSource source() {
    return source;
  }
  
  public void status(JobStatus status) {
    this.status = status;
  }
  
  public JobStatus status() {
    return status;
  }
  
  public void timestamp(Instant timestamp) {
    this.timestamp = timestamp;
  }
  
  public Instant timestamp() {
    return timestamp;
  }
  
  @Override
  public String toString() {
    return "AuditLog[id=" + id
        + ", jobId=" + jobId
        + ", timestamp=" + timestamp
        + ", source=" + source
        + ", status=" + status
        + ", content=" + content
        + ", progrss=" + progress
        + "]";
  }
  
}
