
# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.ingest-status-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-status-out.exchange.name=emdb.events
mp.messaging.outgoing.ingest-status-out.exchange.type=topic
mp.messaging.outgoing.ingest-status-out.routing-key=ingest.status.changed
