package com.erdouglass.emdb.media;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

@MappedSuperclass
public class Media {
  public static final String SEQUENCE_GENERATOR = "sequence_generator";
  
  /// The timestamp when this entity was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant createdAt;
  
  /// The primary key is generated by a database sequence that is intentionally 
  /// exposed to the public giving it business meaning. This is URL friendly and
  /// makes it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;
  
  /// The timestamp when this entity was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modifiedAt;

  /// Default protected constructor for JPA and proxying.
  protected Media() {}
  
  public Instant getCreatedAt() {
    return createdAt;
  }
  
  public Long getId() {
    return id;
  }
  
  public Instant getModifiedAt() {
    return modifiedAt;
  }
}
