# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60320

# --------------------------------------------------------------------
# --- DEFAULT gRPC CONFIGURATION
# Must use a separate gRPC server with a dedicated HTTP/2 event loop 
# to handle requests under load.
# --------------------------------------------------------------------
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=60398

# -----------------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# -----------------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.hibernate-orm.database.default-schema=emdb_user
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.flyway.schemas=emdb_user
