plugins {
  id 'java-library'
  id 'eclipse'
}

group = 'com.erdouglass.emdb'
version = '1.0.0-SNAPSHOT'

dependencies {
  compileOnly         enforcedPlatform(libs.quarkus.bom)
  annotationProcessor enforcedPlatform(libs.quarkus.bom)
  annotationProcessor libs.lombok
  annotationProcessor libs.lombok.mapstruct.binding
  annotationProcessor libs.hibernate.processor
  annotationProcessor libs.mapstruct.processor
  
  implementation project(':common-messaging')
  implementation project(':common-rest')
  implementation project(':common-util')
  implementation project(':emdb-ingest-api')
  implementation project(':emdb-media-api')
  
  implementation libs.jug
  
  compileOnly libs.jakarta.cdi.api
  compileOnly libs.jakarta.data.api
  compileOnly libs.jakarta.persistence.api
  compileOnly libs.jakarta.validation.api
  compileOnly libs.jakarta.ws.rs.api
  compileOnly libs.jboss.logging
  compileOnly libs.lombok
  compileOnly libs.mapstruct
  compileOnly libs.microprofile.rest.client.api
  compileOnly libs.quarkus.hibernate.orm
  compileOnly libs.smallrye.reactive.messaging.api
  compileOnly libs.smallrye.reactive.messaging.rabbitmq  
}

eclipse {
  classpath {
    file.whenMerged { classpath ->
      def generatedSrcDir = 'build/generated/sources/annotationProcessor/java/main'
      classpath.entries.add(new org.gradle.plugins.ide.eclipse.model.SourceFolder(generatedSrcDir, null))
    }
  }
}
