plugins {
  id 'java-library'
}

group = 'com.erdouglass.emdb'
version = '1.0.0-SNAPSHOT'

dependencies {
  compileOnly         enforcedPlatform(libs.quarkus.bom)
  annotationProcessor enforcedPlatform(libs.quarkus.bom)
  annotationProcessor libs.lombok
  annotationProcessor libs.mapstruct.processor
  
  implementation project(':common-messaging')
  implementation project(':common-util')
  implementation project(':emdb-media-api')
  
  implementation libs.jug
  
  compileOnly libs.jakarta.cdi.api
  compileOnly libs.jboss.logging
  compileOnly libs.lombok
  compileOnly libs.mapstruct
  compileOnly libs.smallrye.reactive.messaging.api
  compileOnly libs.smallrye.reactive.messaging.rabbitmq  
}
