package com.erdouglass.emdb.media.adapter.outbound.movie;

import java.time.LocalDate;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import com.erdouglass.emdb.media.MediaConstants;
import com.erdouglass.emdb.media.domain.movie.Movie;
import com.erdouglass.emdb.media.domain.movie.MovieId;
import com.erdouglass.emdb.media.domain.shared.SourceId;

/// Persistence model of a movie row. Emphatically *not* the domain [Movie].
///
/// This class belongs to the adapter and is shaped by the database, not the
/// ubiquitous language: flat columns, mutable, no behavior. The separation is
/// what keeps JPA annotations, no-arg constructors, and generated values out
/// of the domain model — [MovieMapper] pays the translation toll on purpose.
/// Constraint annotations here are a schema-level backstop; the authoritative
/// rules already ran in the value objects.
@Entity 
@Table(
  name = "movie",
  uniqueConstraints = {
    @UniqueConstraint(name = "uq_movie_source", columnNames = { "source", "source_id" }),
    @UniqueConstraint(name = "uq_movie_uuid", columnNames = { "id" }),
  }
)
class MovieEntity {
  
  /// Internal surrogate key, application-generated ([MovieId] on the domain
  /// side). Never exposed publicly.
  @Column(nullable = false, updatable = false)
  private UUID id;
  
  @Column(name = "original_language", nullable = false, length = MediaConstants.ISO_639_1_LENGTH)
  private String originalLanguage;
  
  /// The primary key is generated by a database sequence upon insertion. It is
  /// URL friendly making it easy for users to discover and link to content.
  @Id
  @SequenceGenerator(
      name = "movie_seq", 
      sequenceName = "movie_sequence", 
      initialValue = 1, 
      allocationSize = 1)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "movie_seq")
  private Long publicId;
  
  @Column(name = "release_date")
  private LocalDate releaseDate;
  
  /// External provenance pair ([SourceId] on the domain side), stored as the
  /// canonical lowercase token plus provider id. Guarded by the
  /// `uq_movie_source` unique constraint — the enforcement point for the
  /// cross-aggregate rule that no two movies share an external identity.
  @Column(nullable = false, length = 16)
  private String source;
  
  @Column(name = "source_id", nullable = false, length = 64)
  private String sourceId;
  
  @Column(nullable = false, length = MediaConstants.TITLE_MAX_LENGTH)
  private String title;
  
  MovieEntity() {}
  
  MovieEntity(UUID id) {
    this.id = id;
  }
  
  public UUID getId() {
    return id;
  }
  
  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }
  
  public String getOriginalLanguage() {
    return originalLanguage;
  }
  
  public void setPublicId(Long publicId) {
    this.publicId = publicId;
  }
  
  public Long getPublicId() {
    return publicId;
  }
  
  public void setReleaseDate(LocalDate releaseDate) {
    this.releaseDate = releaseDate;
  }
  
  public LocalDate getReleaseDate() {
    return releaseDate;
  }
  
  public void setSource(String source) {
    this.source = source;
  }
  
  public String getSource() {
    return source;
  }
  
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }
  
  public String getSourceId() {
    return sourceId;
  }
  
  public void setTitle(String title) {
    this.title = title;
  }

  public String getTitle() {
    return title;
  }    
  
  @Override
  public String toString() {
    return "Movie[id=" + getId()
        + ", publicId=" + getPublicId()
        + ", source=" + getSource()
        + ", sourceId=" + getSourceId()
        + ", title=" + getTitle() 
        + ", releaseDate=" + getReleaseDate()
        + "]";
  }
}
