package com.erdouglass.emdb.media.adapter.outbound.movie;

import java.time.LocalDate;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import org.hibernate.annotations.Generated;

import com.erdouglass.common.validation.DateRange;
import com.erdouglass.emdb.media.MediaConstants;

@Entity 
@Table(name = "movie")
class MovieEntity {

  /// The movie id is a surrogate key generated by the application and never
  /// gets exposed to the public.
  @Id
  private UUID id;
  
  /// The movies public id is a database generated sequence that is URL friendly.
  @Generated
  @Column(name = "public_id", nullable = false, unique = true, updatable = false)
  private Long publicId;
  
  @Column(name = "release_date")
  @DateRange(min = MediaConstants.MOVIE_MIN_DATE, max = MediaConstants.MAX_DATE)
  private LocalDate releaseDate;
  
  @Column(nullable = false, length = 16)
  private String source;
  
  @Column(name = "source_id", nullable = false, length = 64)
  private String sourceId;
  
  @NotBlank
  @Size(max = MediaConstants.TITLE_MAX_LENGTH)
  private String title;
  
  MovieEntity() {}
  
  public void setId(UUID id) {
    this.id = id;
  }
  
  public UUID getId() {
    return id;
  }
  
  public Long getPublicId() {
    return publicId;
  }
  
  public void setReleaseDate(LocalDate releaseDate) {
    this.releaseDate = releaseDate;
  }
  
  public LocalDate getReleaseDate() {
    return releaseDate;
  }
  
  public void setSource(String source) {
    this.source = source;
  }
  
  public String getSource() {
    return source;
  }
  
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }
  
  public String getSourceId() {
    return sourceId;
  }
  
  public void setTitle(String title) {
    this.title = title;
  }

  public String getTitle() {
    return title;
  }    
  
  @Override
  public String toString() {
    return "Movie[id=" + getId()
        + ", publicId=" + getPublicId()
        + ", source=" + getSource()
        + ", sourceId=" + getSourceId()
        + ", title=" + getTitle() 
        + ", releaseDate=" + getReleaseDate()
        + "]";
  }
}
