{
 "title": "EMDB",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "EMDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_usage{application=~\"scraper\"}[5m]) * 100",
       "legendFormat": "{{application}} CPU Usage"
      },
      {
       "expr": "rate(process_cpu_usage{application=~\"media\"}[5m]) * 100",
       "legendFormat": "{{application}} CPU Usage"
      },
      {
       "expr": "rate(process_cpu_usage{application=~\"gateway\"}[5m]) * 100",
       "legendFormat": "{{application}} CPU Usage"
      },
      {
       "expr": "rate(process_cpu_usage{application=~\"job\"}[5m]) * 100",
       "legendFormat": "{{application}} CPU Usage"
      },
      {
       "expr": "rate(process_cpu_usage{application=~\"scheduler\"}[5m]) * 100",
       "legendFormat": "{{application}} CPU Usage"
      }
     ]
    }
   ]
  },
  { "title": "Media Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"media\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"media\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"media\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"media\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"media\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"media\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Average Ingest Queue Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(media)(emdb_ingest_queue_duration_seconds_sum{}) / sum by(media)(emdb_ingest_queue_duration_seconds_count{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Movie Ingest Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(media)(emdb_ingest_duration_seconds_sum{media=\"movie\"}) / sum by(media)(emdb_ingest_duration_seconds_count{media=\"movie\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Series Ingest Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(media)(emdb_ingest_duration_seconds_sum{media=\"series\"}) / sum by(media)(emdb_ingest_duration_seconds_count{media=\"series\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Person Ingest Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(media)(emdb_ingest_duration_seconds_sum{media=\"person\"}) / sum by(media)(emdb_ingest_duration_seconds_count{media=\"person\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emdb_scrape_duration_seconds_count{application=\"media\"}",
     "legendFormat": "{{media}}"
    }
   ]
  },
  {
   "title": "Average Movie Scrape Duration",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emdb_scrape_duration_seconds_sum{media=\"movie\"} / emdb_scrape_duration_seconds_count{media=\"movie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Series Scrape Duration",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emdb_scrape_duration_seconds_sum{media=\"series\"} / emdb_scrape_duration_seconds_count{media=\"series\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Person Scrape Duration",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "emdb_scrape_duration_seconds_sum{media=\"person\"} / emdb_scrape_duration_seconds_count{media=\"person\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TMDB Request Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (clientName) (http_client_requests_seconds_count{clientName=~\"tmdb.*\"}),\n  \"clientName\", \"$1\", \"clientName\", \"tmdb-(.*)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TMDB Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (clientName) (http_client_requests_seconds_sum{clientName=~\"tmdb.*\"})\n  /\n  sum by (clientName) (http_client_requests_seconds_count{clientName=~\"tmdb.*\"}),\n  \"clientName\", \"$1\", \"clientName\", \"tmdb-(.*)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}