
    create table ingest.ingest_job (
        id uuid not null,
        ingest_type varchar(16) not null check ((ingest_type in ('MOVIE','PERSON','SERIES'))),
        stage varchar(16) not null check ((stage in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        submitted_at timestamp(6) with time zone not null,
        tmdb_id integer not null,
        version bigint not null,
        primary key (id)
    );

    create table ingest.ingest_stage (
        id bigint generated by default as identity,
        job_id uuid not null,
        message varchar(1000) not null,
        occurred_at timestamp(6) with time zone not null,
        stage varchar(16) not null check ((stage in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        primary key (id)
    );
