# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60318

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.status-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.status-events-in.exchange.name=emdb.events
mp.messaging.incoming.status-events-in.exchange.type=fanout
