# -----------------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# -----------------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60318

# -----------------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# max-outstanding-messages=1 ensures status events are processed serially which
# matches the system throughput.
# -----------------------------------------------------------------------------
mp.messaging.incoming.status-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.status-events-in.exchange.type=direct
mp.messaging.incoming.status-events-in.exchange.name=emdb.events
mp.messaging.incoming.status-events-in.routing-keys=status.changed
mp.messaging.incoming.status-events-in.queue.name=emdb-notification.status-events
mp.messaging.incoming.status-events-in.max-outstanding-messages=1

# --------------------------------------------------------------------
# --- DEFAULT gRPC CONFIGURATION
# Must use a separate gRPC server with a dedicated HTTP/2 event loop 
# to handle concurrent requests under load.
# --------------------------------------------------------------------
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=60397

# -----------------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# -----------------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.hibernate-orm.database.default-schema=emdb_notification
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.flyway.schemas=emdb_notification
