services:
  
  rabbitmq:
    image: rabbitmq:4.3.6-management
    container_name: rabbitmq 
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   
    networks:
      - erd
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5 
            
  emdb-ingest:
    image: emdb-ingest:latest
    container_name: emdb-ingest
    build:
      context: ./emdb-ingest-service
      dockerfile: src/main/docker/Dockerfile
    ports:
      - 60330:60310
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./emdb-ingest-service/.env
    networks:
      - erd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60310/api/v1/q/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy

  emdb-scraper:
    image: emdb-scraper:latest
    container_name: emdb-scraper
    build:
      context: ./emdb-scraper-service
      dockerfile: src/main/docker/Dockerfile
    ports:
      - 60334:60314
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./emdb-scraper-service/.env
    networks:
      - erd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60314/emdb/api/v1/q/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
                
volumes:
  rabbitmq_data:
    
networks:
  erd:
    name: erd
    external: true
