# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60316

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.save-movie-in.connector=smallrye-rabbitmq
mp.messaging.incoming.save-movie-in.exchange.name=emdb.commands
mp.messaging.incoming.save-movie-in.exchange.type=direct
mp.messaging.incoming.save-movie-in.routing-keys=movie.save
mp.messaging.incoming.save-movie-in.queue.name=emdb-media.save-movie
mp.messaging.incoming.save-movie-in.auto-bind-dlq=true
mp.messaging.incoming.save-movie-in.dead-letter-exchange=emdb.commands.dlx
mp.messaging.incoming.save-movie-in.dead-letter-routing-key=movie.save.dlq
mp.messaging.incoming.save-movie-in.dead-letter-queue-name=emdb-media.save-movie.dlq

mp.messaging.incoming.movie-dlq-in.connector=smallrye-rabbitmq
mp.messaging.incoming.movie-dlq-in.exchange.name=emdb.commands.dlx
mp.messaging.incoming.movie-dlq-in.exchange.type=direct
mp.messaging.incoming.movie-dlq-in.routing-keys=movie.save.dlq
mp.messaging.incoming.movie-dlq-in.queue.name=emdb-media.save-movie.dlq

mp.messaging.incoming.save-person-in.connector=smallrye-rabbitmq
mp.messaging.incoming.save-person-in.exchange.name=emdb.commands
mp.messaging.incoming.save-person-in.exchange.type=direct
mp.messaging.incoming.save-person-in.routing-keys=person.save
mp.messaging.incoming.save-person-in.queue.name=emdb-media.save-person
mp.messaging.incoming.save-person-in.auto-bind-dlq=true
mp.messaging.incoming.save-person-in.dead-letter-exchange=emdb.commands.dlx
mp.messaging.incoming.save-person-in.dead-letter-routing-key=person.save.dlq
mp.messaging.incoming.save-person-in.dead-letter-queue-name=emdb-media.save-person.dlq

mp.messaging.incoming.person-dlq-in.connector=smallrye-rabbitmq
mp.messaging.incoming.person-dlq-in.exchange.name=emdb.commands.dlx
mp.messaging.incoming.person-dlq-in.exchange.type=direct
mp.messaging.incoming.person-dlq-in.routing-keys=person.save.dlq
mp.messaging.incoming.person-dlq-in.queue.name=emdb-media.save-person.dlq

mp.messaging.incoming.save-series-in.connector=smallrye-rabbitmq
mp.messaging.incoming.save-series-in.exchange.name=emdb.commands
mp.messaging.incoming.save-series-in.exchange.type=direct
mp.messaging.incoming.save-series-in.routing-keys=series.save
mp.messaging.incoming.save-series-in.queue.name=emdb-media.save-series
mp.messaging.incoming.save-series-in.auto-bind-dlq=true
mp.messaging.incoming.save-series-in.dead-letter-exchange=emdb.commands.dlx
mp.messaging.incoming.save-series-in.dead-letter-routing-key=series.save.dlq
mp.messaging.incoming.save-series-in.dead-letter-queue-name=emdb-media.save-series.dlq

mp.messaging.incoming.series-dlq-in.connector=smallrye-rabbitmq
mp.messaging.incoming.series-dlq-in.exchange.name=emdb.commands.dlx
mp.messaging.incoming.series-dlq-in.exchange.type=direct
mp.messaging.incoming.series-dlq-in.routing-keys=series.save.dlq
mp.messaging.incoming.series-dlq-in.queue.name=emdb-media.save-series.dlq

mp.messaging.outgoing.ingest-media-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-media-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-media-out.exchange.type=direct
mp.messaging.outgoing.ingest-media-out.default-routing-key=media.ingest

# --------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.datasource.jdbc.additional-jdbc-properties.reWriteBatchedInserts=true
quarkus.hibernate-orm.database.default-schema=emdb_media
quarkus.hibernate-orm.jdbc.statement-batch-size=50
#quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.schemas=emdb_media
