package com.erdouglass.emdb.media.domain.internal;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

import org.hibernate.Hibernate;
import org.hibernate.annotations.UuidGenerator;

import com.erdouglass.emdb.media.credit.CreditType;
import com.erdouglass.emdb.media.domain.person.Person;

@Entity
@Table(name = "Credits")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
public class Credit {
  private static final int CREDIT_TYPE_MAX_LENGTH = 4;
    
  /// The primary key is a surrogate key generated by the database using 
  /// [UuidGenerator.Style.TIME] strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  @PositiveOrZero
  @Column(name = "credit_order")
  private Integer order;
  
  /// The @JoinColumn annotation maps the {@link Person#id} primary key to the
  /// foreign key in the Credits table. A {@code Credit} can't exist without a 
  /// {@link Movie} or {@link Series}.
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "person_id", updatable = false, nullable = false)
  private Person person; 
  
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "credit_type", updatable = false, length = CREDIT_TYPE_MAX_LENGTH)
  private CreditType type;  
  
  public Credit() {}

  public UUID getId() {
    return id;
  }
  
  public void setOrder(Integer order) {
    this.order = order;
  }
  
  public Integer getOrder() {
    return order;
  } 
  
  public void setPerson(Person person) {
    this.person = person;
  }
  
  public Person getPerson() {
    return person;
  }
  
  public void setType(CreditType type) {
    this.type = type;
  }
  
  public CreditType getType() {
    return type;
  }  
  
  @Override
  public boolean equals(Object o) {
    if (this == o) 
      return true;
    if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) 
      return false;
    Credit other = (Credit) o;
    return getId() != null && getId().equals(other.getId());
  }

  @Override
  public int hashCode() {
    return Hibernate.getClass(this).hashCode();
  }
}
