package com.erdouglass.emdb.media.domain.internal;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.NotBlank;

import org.hibernate.Hibernate;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

@MappedSuperclass
public abstract class UuidMedia {

  /// The timestamp when this entity was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant createdAt;
  
  /// The primary key is a surrogate key generated by the database using 
  /// [UuidGenerator.Style.TIME] strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  /// The timestamp when this entity was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modifiedAt;
  
  /// The TMDB id provides a stable immutable natural key.
  @NotBlank
  @Column(name = "tmdb_id", unique = true, updatable = false)
  private String tmdbId;
  
  /// Default protected constructor for JPA.
  protected UuidMedia() {}
  
  protected UuidMedia(final String tmdbId) {
    this.tmdbId = tmdbId;
  }
  
  public Instant getCreatedAt() {
    return createdAt;
  }
  
  public UUID getId() {
    return id;
  }
  
  public Instant getModifiedAt() {
    return modifiedAt;
  }
  
  public String getTmdbId() {
    return tmdbId;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null || Hibernate.getClass(this) != Hibernate.getClass(obj))
      return false;
    UuidMedia other = (UuidMedia) obj;
    return Objects.equals(getTmdbId(), other.getTmdbId());
  }
  
  @Override
  public int hashCode() {
    return Objects.hash(getTmdbId());
  }
}
