package com.erdouglass.emdb.media.person;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Size;

import com.erdouglass.common.validation.DateRange;
import com.erdouglass.emdb.common.Configuration;
import com.erdouglass.emdb.media.Gender;
import com.erdouglass.emdb.media.PersonConstants;
import com.erdouglass.emdb.media.credit.Credit;
import com.erdouglass.emdb.media.credit._Credit;
import com.erdouglass.emdb.media.internal.Media;
import com.erdouglass.emdb.media.internal.Show;
import com.erdouglass.emdb.media.show.ShowConstants;

/// A person entity — an actor, director, or other contributor credited on a
/// [Show]. Extends [Media] with biographical fields (biography, birth and death
/// dates, birth place), display data (name, gender, homepage), and the profile
/// image reference kept both as the internal EMDB [UUID] and the original TMDB
/// asset path.
///
/// The numeric primary key is generated from a database sequence and is
/// deliberately exposed in public URLs to give it business meaning.
@Entity
@Table(name = "People")
@SequenceGenerator(
    name = Media.SEQUENCE_GENERATOR, 
    sequenceName = "person_sequence", 
    initialValue = 1, 
    allocationSize = 50)
public class Person extends Media<Integer> {
  
  @Size(max = PersonConstants.BIOGRAPHY_MAX_LENGTH)
  private String biography;
  
  @Past
  @Column(name = "birth_date")
  @DateRange(min = PersonConstants.MIN_DATE, max = PersonConstants.MAX_DATE)
  private LocalDate birthDate;
  
  @Column(name = "birth_place")
  @Size(max = PersonConstants.BIRTH_PLACE_MAX_LENGTH)
  private String birthPlace;
  
  /// The credits collection in a person is a bidirectional association 
  /// specified by the mappedBy field which maps the {@link Person#id} primary
  /// key to the foreign key in the Credits table.
  @OneToMany(mappedBy = _Credit.PERSON)
  private List<Credit> credits = new ArrayList<>();   
  
  @Past
  @Column(name = "death_date")
  @DateRange(min = PersonConstants.MIN_DATE, max = PersonConstants.MAX_DATE)
  private LocalDate deathDate;
  
  @NotNull 
  @Enumerated(EnumType.STRING)
  @Column(length = PersonConstants.GENDER_MAX_LENGTH)
  private Gender gender;
  
  @Size(max = Configuration.URL_MAX_LENGTH)
  private String homepage;
  
  /// The primary key is generated by a database sequence that is intentionally 
  /// exposed to the public giving it business meaning. This is URL friendly and
  /// makes it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;
  
  @NotBlank
  @Size(max = PersonConstants.NAME_MAX_LENGTH)
  private String name;
  
  @Column(unique = true)
  private UUID profile;
  
  @Column(name="tmdb_profile", unique = true)
  @Size(min = ShowConstants.POSTER_MIN_LENGTH, max = ShowConstants.POSTER_MAX_LENGTH)
  private String tmdbProfile;
  
  /// Default constructor required by JPA.
  protected Person() {}
  
  protected Person(final int tmdbId) {
    super(tmdbId);
  }
    
  public void setBiography(String biography) {
    this.biography = biography;
  }

  public String getBiography() {
    return biography;
  }
  
  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }
  
  public LocalDate getBirthDate() {
    return birthDate;
  }
  
  public void setBirthPlace(String birthPlace) {
    this.birthPlace = birthPlace;
  }
  
  public String getBirthPlace() {
    return birthPlace;
  }
  
  public void setCredits(List<Credit> credits) {
    this.credits = new ArrayList<>(credits);
  }
  
  public List<Credit> getCredits() {
    return List.copyOf(credits);
  }
  
  public void setDeathDate(LocalDate deathDate) {
    this.deathDate = deathDate;
  }

  public LocalDate getDeathDate() {
    return deathDate;
  }
  
  public void setGender(Gender gender) {
    this.gender = gender;
  }

  public Gender getGender() {
    return gender;
  }
  
  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public String getHomepage() {
    return homepage;
  }
  
  public Long getId() {
    return id;
  }
  
  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
  
  public void setProfile(UUID profile) {
    this.profile = profile;
  }

  public UUID getProfile() {
    return profile;
  }
  
  public void setTmdbProfile(String tmdbProfile) {
    this.tmdbProfile = tmdbProfile;
  }
  
  public String getTmdbProfile() {
    return tmdbProfile;
  } 
  
  @Override
  public String toString() {
    return "Person[id=" + getId()
    + ", tmdbId=" + getTmdbId() 
    + ", name=" + getName() 
    + ", birthDate=" + getBirthDate()
    + ", profile=" + getProfile()
    + "]";
  }
}
