global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'scraper'
    metrics_path: '/api/q/metrics'
    static_configs:
      - targets: ['emdb-scraper:60314'] 
        labels:
          application: 'scraper'
    
  - job_name: 'media'
    metrics_path: '/api/q/metrics'
    static_configs:
      - targets: ['emdb-media:60316'] 
        labels:
          application: 'media'
