plugins {
  id 'java-library'
}

group = 'com.erdouglass.emdb'
version = '1.0.0-SNAPSHOT'

dependencies {
  compileOnly         enforcedPlatform(libs.quarkus.bom)
  annotationProcessor enforcedPlatform(libs.quarkus.bom)
  annotationProcessor libs.mapstruct.processor
   
  implementation project(':emdb-ingest-api')
  implementation project(':emdb-ingest-ws')
  implementation project(':emdb-media-api')
  
  implementation libs.jug
  
  compileOnly libs.jackson.databind
  compileOnly libs.jakarta.cdi.api
  compileOnly libs.jakarta.validation.api
  compileOnly libs.jboss.logging
  compileOnly libs.mapstruct
  compileOnly libs.microprofile.config.api
  compileOnly libs.microprofile.rest.client.api
  compileOnly libs.smallrye.reactive.messaging.api
  compileOnly libs.smallrye.reactive.messaging.rabbitmq
}



