package com.erdouglass.emdb.media.internal;

import java.time.Instant;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.SequenceGenerator;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import org.hibernate.Hibernate;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/// Base class for all media entities. Provides shared identity and audit
/// fields ([#id], [#createdAt], [#modifiedAt]) and declares the JPA sequence
/// generator name that concrete subclasses bind to their own database sequence
/// via [SequenceGenerator].
@MappedSuperclass
public abstract class Media {
  public static final String SEQUENCE_GENERATOR = "sequence_generator";
  
  /// The timestamp when this entity was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant createdAt;
  
  /// The primary key is generated by a database sequence that is intentionally 
  /// exposed to the public giving it business meaning. This is URL friendly and
  /// makes it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;
  
  /// The timestamp when this entity was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modifiedAt;
  
  /// The TMDB id provides a stable immutable natural key.
  @NotNull
  @Positive
  @Column(name = "tmdb_id", unique = true, updatable = false)
  private Integer tmdbId;

  /// Default protected constructor for JPA.
  protected Media() {}
  
  public Media(final int tmdbId) {
    this.tmdbId = tmdbId;
  }
  
  public Instant getCreatedAt() {
    return createdAt;
  }
  
  public Long getId() {
    return id;
  }
  
  public Instant getModifiedAt() {
    return modifiedAt;
  }
  
  public Integer getTmdbId() {
    return tmdbId;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null || Hibernate.getClass(this) != Hibernate.getClass(obj))
      return false;
    Media other = (Media) obj;
    return Objects.equals(getTmdbId(), other.getTmdbId());
  }
  
  @Override
  public int hashCode() {
    return Objects.hash(getTmdbId());
  }
}
