plugins {
  id 'java-library'
  id 'eclipse'
  id 'org.gradlex.extra-java-module-info' version '1.12'
}

group = 'com.erdouglass.emdb'
version = '1.0.0-SNAPSHOT'

dependencies {
  compileOnly enforcedPlatform(libs.quarkus.bom)
  annotationProcessor enforcedPlatform(libs.quarkus.bom)
  
  annotationProcessor libs.hibernate.processor
  annotationProcessor libs.mapstruct.processor
  
  implementation project(':common-validation')
  implementation project(':emdb-common-api')
  implementation project(':emdb-media-api')
  
  implementation libs.jug
  
  compileOnly libs.hibernate.core
  compileOnly libs.jakarta.cdi.api
  compileOnly libs.jakarta.data.api
  compileOnly libs.jakarta.persistence.api
  compileOnly libs.jakarta.validation.api
  compileOnly libs.jboss.logging
  compileOnly libs.mapstruct
  compileOnly libs.microprofile.config.api 
}

extraJavaModuleInfo {
  failOnMissingModuleInfo = false
  automaticModule('org.eclipse.microprofile.config:microprofile-config-api', 'microprofile.config.api')
}

eclipse {
  classpath {
    file.whenMerged { classpath ->
      def generatedSrcDir = 'build/generated/sources/annotationProcessor/java/main'
      classpath.entries.add(new org.gradle.plugins.ide.eclipse.model.SourceFolder(generatedSrcDir, null))
    }
  }
}
