# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-media/api

emdb.image.data=/home/erdouglass/projects/emdb/media-data-dev/images
emdb.movie.data=/home/erdouglass/projects/emdb/media-data-dev/movies
emdb.series.data=/home/erdouglass/projects/emdb/media-data-dev/series
emdb.person.data=/home/erdouglass/projects/emdb/media-data-dev/people

# --------------------------------------------------------------------
# --- DEVELOPMENT TEST CONTAINERS CONFIGURATION
# --------------------------------------------------------------------
quarkus.rabbitmq.devservices.enabled=false
rabbitmq-host=localhost
rabbitmq-port=5673

# --------------------------------------------------------------------
# --- DEVELOPMENT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dev
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-at-start=true

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-media-service/logs/emdb-media-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.SQL".handlers=LOG_FILE
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.messaging".level=INFO
quarkus.log.category."com.erdouglass.messaging".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=INFO
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.common.api".level=INFO
quarkus.log.category."com.erdouglass.emdb.common.api".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.media".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.media".handlers=LOG_FILE
