# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60316
quarkus.grpc.server.use-separate-server=false
