# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/api/v1
quarkus.http.port=60312

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.movies-scraped.connector=smallrye-kafka
mp.messaging.incoming.movies-scraped.topic=emdb.movies.scraped
mp.messaging.incoming.movies-scraped.group.id=emdb-media-service
mp.messaging.incoming.movies-scraped.auto.offset.reset=earliest
mp.messaging.incoming.movies-scraped.key.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer

mp.messaging.outgoing.media-events.connector=smallrye-kafka
mp.messaging.outgoing.media-events.topic=emdb.media.events
mp.messaging.outgoing.media-events.key.serializer=org.apache.kafka.common.serialization.UUIDSerializer
mp.messaging.outgoing.media-events.acks=all

# --------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.hibernate-orm.database.default-schema=media
quarkus.flyway.default-schema=media
quarkus.flyway.baseline-on-migrate=true
