# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-media/api

# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE LOGGING
# --------------------------------------------------------------------
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-media-service/logs/emdb-media-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.SQL".handlers=LOG_FILE
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.media".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.media".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=DEBUG
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE

# --------------------------------------------------------------------
# --- ALL PROFILES DATABASE
# --------------------------------------------------------------------
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dev
quarkus.flyway.clean-at-start=true
