# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-media/api
quarkus.http.port=60312
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# max-outstanding-messages=1 ensures ingest messages are processed serially which
# prevents the TMDB server from being overwhelmed.
# --------------------------------------------------------------------
mp.messaging.incoming.ingest-media-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-media-in.exchange.name=emdb.commands
mp.messaging.incoming.ingest-media-in.exchange.type=direct
mp.messaging.incoming.ingest-media-in.routing-keys=ingest.media
mp.messaging.incoming.ingest-media-in.queue.name=ingest-media
mp.messaging.incoming.ingest-media-in.max-outstanding-messages=1

mp.messaging.incoming.ingest-media-in.auto-bind-dlq=true
mp.messaging.incoming.ingest-media-in.dlx.declare=true
mp.messaging.incoming.ingest-media-in.dead-letter-exchange=emdb.commands.dlx
mp.messaging.incoming.ingest-media-in.dead-letter-exchange-type=direct
mp.messaging.incoming.ingest-media-in.dead-letter-queue-name=ingest-media.dlq
mp.messaging.incoming.ingest-media-in.dead-letter-routing-key=ingest-media

mp.messaging.incoming.ingest-media-dlq-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-media-dlq-in.exchange.name=emdb.commands.dlx
mp.messaging.incoming.ingest-media-dlq-in.exchange.type=direct
mp.messaging.incoming.ingest-media-dlq-in.queue.name=ingest-media.dlq
mp.messaging.incoming.ingest-media-dlq-in.routing-keys=ingest-media
mp.messaging.incoming.ingest-media-dlq-in.failure-strategy=fail
