# --------------------------------------------------------------------
# --- PRODUCTION CONFIGURATION
# --------------------------------------------------------------------
quarkus.otel.exporter.otlp.traces.endpoint=http://jaeger:4317

# --------------------------------------------------------------------
# --- PRODUCTION LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.console.level=INFO
quarkus.log.json.log-format=ecs
quarkus.log.json.additional-field."service.name".value=emdb-media-service
quarkus.log.json.additional-field."service.name".type=string

# --------------------------------------------------------------------
# --- PRODUCTION MESSAGING CONFIGURATION
# --------------------------------------------------------------------
rabbitmq-host=rabbitmq

# --------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/prod
# TODO: Set these to false once the production database has been finalized.
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-at-start=true
