# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-media/api

# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE LOGGING
# --------------------------------------------------------------------
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-media-service/logs/emdb-media-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."com.erdouglass".level=DEBUG
quarkus.log.category."com.erdouglass".handlers=LOG_FILE
