package com.erdouglass.emdb.notification.entity;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import com.erdouglass.emdb.common.MediaType;
import com.erdouglass.emdb.common.ShowConstants;
import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestSource;
import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestStatus;

@Entity
public class Ingest {

  @Positive
  @Column(name = "emdb_id")
  private Long emdbId;
  
  /// The primary key is generated by the application.
  @Id
  private UUID id;
  
  @Column(name = "last_modified")
  private Instant lastModified;
  
  private String message;
  
  @Size(max = ShowConstants.TITLE_MAX_LENGTH)
  private String name;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestSource source;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestStatus status;
  
  @NotNull
  @Positive
  @Column(name = "tmdb_id", updatable = false)
  private Integer tmdbId;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private MediaType type;
  
  public Ingest() {
    
  }
  
  public void setEmdbId(Long emdbId) {
    this.emdbId = emdbId;
  }
  
  public Long getEmdbId() {
    return emdbId;
  }
  
  public void setId(UUID id) {
    this.id = id;
  }
  
  public UUID getId() {
    return id;
  }
  
  public void setLastModified(Instant lastModified) {
    this.lastModified = lastModified;
  }
  
  public Instant getLastModified() {
    return lastModified;
  }
  
  public void setMessage(String message) {
    this.message = message;
  }
  
  public String getMessage() {
    return message;
  }
  
  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
  
  public void setSource(IngestSource source) {
    this.source = source;
  }
  
  public IngestSource getSource() {
    return source;
  }
  
  public void setStatus(IngestStatus status) {
    this.status = status;
  }
  
  public IngestStatus getStatus() {
    return status;
  }
  
  public void setTmdbId(Integer tmdbId) {
    this.tmdbId = tmdbId;
  }
  
  public Integer getTmdbId() {
    return tmdbId;
  }
  
  public void setType(MediaType type) {
    this.type = type;
  }
  
  public MediaType getType() {
    return type;
  }
  
  @Override
  public String toString() {
    return "IngestJob[id=" + id
        + ", lastModified=" + lastModified
        + ", status=" + status
        + ", emdbId=" + emdbId
        + ", tmdbId=" + tmdbId
        + ", source=" + source
        + ", type=" + type
        + "]";
  }
}
