package com.erdouglass.emdb.notification.entity;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

import com.erdouglass.emdb.common.api.messaging.IngestSource;
import com.erdouglass.emdb.common.api.messaging.IngestStatus;
import com.erdouglass.emdb.common.api.messaging.IngestStatusChanged;

/// Append-only record of a single status transition for an ingest.
///
/// Each row corresponds to one [IngestStatusChanged] event. Together they
/// form the audit trail rendered in the UI when a row is expanded. The
/// `(ingest_id, status, last_modified)` unique constraint protects against
/// duplicate inserts on broker redelivery.
@Entity
@Table(name = "ingest_status_change",
indexes = {
    @Index(name = "idx_iscn_ingest_last_modified",
           columnList = "ingest_id, last_modified DESC")
    },
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_iscn_ingest_status_last_modified",
                          columnNames = {"ingest_id", "status", "last_modified"})
    })
public class IngestStatusChange {
  
  /// The primary key is generated by the database as a surrogate key that has no 
  /// business meaning and is never exposed outside the application. 
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  
  /// The @JoinColumn annotation maps the [Ingest#id] primary key to the 
  /// foreign key in the Status_Events table.
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "ingest_id", nullable = false,
              foreignKey = @ForeignKey(name = "fk_iscn_ingest"))
  private Ingest ingest;
  
  @NotNull
  @Column(name = "last_modified")
  private Instant lastModified;
  
  @NotNull 
  private String message;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestSource source;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestStatus status;
  
  public IngestStatusChange() {
    
  }
  
  public Long getId() {
    return id;
  }
  
  public void setIngest(Ingest ingest) {
    this.ingest = ingest;
  }
  
  public Ingest getIngest() {
    return ingest;
  }
  
  public void setLastModified(Instant lastModified) {
    this.lastModified = lastModified;
  }
  
  public Instant getLastModified() {
    return lastModified;
  }
  
  public void setMessage(String message) {
    this.message = message;
  }
  
  public String getMessage() {
    return message;
  }
  
  public void setSource(IngestSource source) {
    this.source = source;
  }
  
  public IngestSource getSource() {
    return source;
  }
  
  public void setStatus(IngestStatus status) {
    this.status = status;
  }
  
  public IngestStatus getStatus() {
    return status;
  }
  
  @Override
  public String toString() {
    return "IngestStatusChange[lastModified=" + lastModified
        + ", status=" + status
        + ", source=" + source
        + ", message=" + message
        + "]";
  }
}
