package com.erdouglass.emdb.notification.entity;

import java.time.Instant;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;

import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestSource;
import com.erdouglass.emdb.common.event.IngestStatusChanged.IngestStatus;

@Entity
@Table(name = "status_events",
uniqueConstraints = @UniqueConstraint(
    name = "uq_status_events_ingest_status",
    columnNames = {"correlation_id", "status"}))
public class StatusEvent {
  
  @NotNull
  private Instant created;
  
  /// The primary key is generated by the database as a surrogate key that has no 
  /// business meaning and is never exposed outside the application. 
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  
  /// The @JoinColumn annotation maps the [Ingest#id] primary key to the 
  /// foreign key in the Status_Events table.
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "correlation_id", nullable = false)
  private Ingest ingest;
  
  private String message;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestSource source;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private IngestStatus status;

  public StatusEvent() {
    
  }
  
  public void setCreated(Instant created) {
    this.created = created;
  }
  
  public Instant getCreated() {
    return created;
  }
  
  public Long getId() {
    return id;
  }
  
  public void setIngest(Ingest ingest) {
    this.ingest = ingest;
  }
  
  public Ingest getIngest() {
    return ingest;
  }
  
  public void setMessage(String message) {
    this.message = message;
  }
  
  public String getMessage() {
    return message;
  }
  
  public void setSource(IngestSource source) {
    this.source = source;
  }
  
  public IngestSource getSource() {
    return source;
  }
  
  public void setStatus(IngestStatus status) {
    this.status = status;
  }
  
  public IngestStatus getStatus() {
    return status;
  }
}
