package com.erdouglass.emdb.media.movie.domain;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.erdouglass.emdb.media.TmdbId;
import com.erdouglass.emdb.media.kernel.Score;
import com.erdouglass.emdb.media.kernel.Version;
import com.erdouglass.emdb.media.movie.domain.exception.LockedMovieException;
import com.erdouglass.emdb.media.movie.domain.exception.StaleMovieException;

/// Movie aggregate.
///
/// A movie carries three identifiers, each with a different lifetime and a
/// different audience:
///
/// * [MovieId] — surrogate id assigned by the application when the aggregate is
///   created. This is the Java identity used by [#equals(Object)] and
///   [#hashCode()], and it is never exposed to the public.
/// * [MoviePublicId] — public-facing id derived from the key the database
///   assigns on first insert. Absent until the aggregate has been persisted.
/// * [TmdbId] — natural id supplied by the upstream catalogue, present from
///   creation and never reassigned.
///
/// State changes go through [#update(MovieDetails)], which returns the list of
/// field-level differences so the caller can audit them; the aggregate does not
/// write to the audit trail itself. [#version()] is likewise read-only here —
/// it is assigned by the persistence layer, and [#checkVersion(Version)] only
/// compares it.
///
/// A locked movie rejects detail changes but still accepts [#lock(boolean)],
/// which is how a lock is lifted.
///
/// Not thread-safe: [#details] and [#locked] are mutable and unsynchronised.
/// Instances are expected to be confined to a single transaction.
public final class Movie {
  private final MovieId id;
  private final MoviePublicId publicId;
  private final TmdbId tmdbId;
  private final Version version;
  
  private MovieDetails details;
  private boolean locked;
  
  private Movie(
      MovieId id, 
      MoviePublicId publicId, 
      TmdbId tmdbId, 
      boolean locked,
      MovieDetails details, 
      Version version) {
    this.id = Objects.requireNonNull(id, "id is required");
    this.publicId = publicId;
    this.tmdbId = Objects.requireNonNull(tmdbId, "tmdbId is required");
    this.locked = locked;
    this.details = Objects.requireNonNull(details, "details are required");
    this.version = version;
  }
  
  /// Creates a new, unpersisted movie aggregate.
  ///
  /// The public id and version stay absent until the movie is written, because
  /// both are derived from database-assigned values. The movie starts unlocked.
  ///
  /// @param id the surrogate id, generated by the caller; must not be `null`
  /// @param tmdbId the natural id from the upstream catalogue
  /// @param details the initial details; must carry at least a title
  /// @return an aggregate that reports empty from [#publicId()] and [#version()]
  /// @throws NullPointerException if `id`, `tmdbId` or `details` is `null`
  public static Movie create(MovieId id, TmdbId tmdbId, MovieDetails details) {
    return new Movie(id, null, tmdbId, false, details, null);
  }
  
  /// Reconstructs a persisted movie from stored state.
  ///
  /// This bypasses every domain rule by design — it restores state that was
  /// already validated when it was written, and a lock must not prevent a locked
  /// movie from being loaded. Only the persistence adapter should call it;
  /// application code creates movies with [#create(MovieId, TmdbId, MovieDetails)].
  ///
  /// @param id the stored surrogate id
  /// @param publicId the stored public id
  /// @param tmdbId the stored natural id
  /// @param locked whether the stored movie is locked against detail changes
  /// @param details the stored details
  /// @param version the stored optimistic-locking version
  /// @return the rehydrated aggregate
  /// @throws NullPointerException if `id`, `tmdbId` or `details` is `null`
  public static Movie rehydrate(
      MovieId id, 
      MoviePublicId publicId, 
      TmdbId tmdbId, 
      boolean locked,
      MovieDetails details, 
      Version version) {
    return new Movie(id, publicId, tmdbId, locked, details, version);
  }
  
  /// Replaces the details wholesale and reports what moved.
  ///
  /// Replacement, not merge: any field absent from `targetDetails` is treated as
  /// cleared and appears in the returned list as a removal. The aggregate is
  /// mutated even when nothing differs, in which case the returned list is
  /// empty and the caller can skip persisting.
  ///
  /// The returned changes are the caller's to audit — this method records
  /// nothing itself.
  ///
  /// @param targetDetails the complete intended details
  /// @return the field-level differences in declaration order, empty when the
  ///         details already matched; never `null`
  /// @throws NullPointerException if `targetDetails` is `null`
  /// @throws LockedMovieException if the movie is locked, including when the
  ///         incoming details are identical to the current ones
  public List<MovieFieldChange> update(MovieDetails targetDetails) {
    Objects.requireNonNull(targetDetails, "details are required");
    var changes = MovieField.diff(this.details, targetDetails);
    if (changes.isEmpty()) {
      return changes;
    }
    if (locked == true) {
      throw new LockedMovieException(publicId().map(MoviePublicId::value).orElse(details.title().value()));
    }
    this.details = targetDetails;
    return changes;
  }
  
  /// Renders the current details as if every populated field had just been added.
  ///
  /// Used to seed the audit trail on insert, so that a title's history starts
  /// with a complete picture rather than with nothing.
  ///
  /// @return one addition per populated field, in declaration order
  public List<MovieFieldChange> changesAsAdded() { return MovieField.diff(null, details); }  
  
  /// Renders the current details as if every populated field had just been
  /// removed.
  ///
  /// Used to close out the audit trail before a delete, so the history records
  /// what was lost rather than ending abruptly.
  ///
  /// @return one removal per populated field, in declaration order
  public List<MovieFieldChange> changesAsDeleted() { return MovieField.diff(details, null); }
  
  /// Asserts that the caller's view of this movie is current.
  ///
  /// Call before mutating on behalf of a client that read the movie earlier; a
  /// mismatch means someone else wrote in between and the caller's edit would
  /// silently discard that write.
  ///
  /// An unpersisted movie has no version and therefore never matches.
  ///
  /// @param expected the version the caller believes it holds
  /// @throws StaleMovieException if this movie has no version, or its version
  ///         differs from `expected`
  /// @throws NullPointerException if `expected` is `null`
  public void checkVersion(Version expected) {
    if (version == null || !version.equals(expected)) {
      throw new StaleMovieException(version.value().toString());
    }
  }
  
  /// Locks or unlocks the movie against detail changes.
  ///
  /// Deliberately exempt from the lock check in [#update(MovieDetails)] —
  /// otherwise a locked movie could never be unlocked. Setting the current
  /// value again is a no-op.
  ///
  /// @param lock `true` to reject subsequent detail changes, `false` to allow
  ///        them
  public void lock(boolean lock) { this.locked = lock; }
  
  /// Getters
  public MovieDetails details() { return details; }  
  public MovieId id() { return id; }  
  public boolean isLocked() { return locked; }
  public Optional<MoviePublicId> publicId() { return Optional.ofNullable(publicId); }
  public TmdbId tmdbId() { return tmdbId; }
  public Optional<Version> version() { return Optional.ofNullable(version); }
  
  @Override
  public int hashCode() {
    return Objects.hash(id);
  }

  /// Compares by surrogate id only.
  ///
  /// Two instances describing the same title are equal even if their details,
  /// lock state or version differ — identity is the aggregate's, not the
  /// snapshot's. Use [#details()] to compare content.
  ///
  /// @param obj the object to compare with
  /// @return `true` if `obj` is a movie with the same [#id()]
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Movie other = (Movie) obj;
    return Objects.equals(id, other.id);
  }
  
  @Override
  public String toString() {
    return getClass().getSimpleName() + "[id=" + id.value()
        + ", publicId=" + publicId().map(MoviePublicId::value).orElse(null)
        + ", tmdbId=" + tmdbId().value()
        + ", version=" + version().map(Version::value).orElse(null)
        + ", locked=" + locked
        + ", title=" + details.title().value()
        + ", releaseDate=" + details.releaseDate().map(ReleaseDate::toLocalDate).orElse(null)
        + ", score=" + details.score().map(Score::value).orElse(null)
        + "]";
  }  
}
