# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
emdb.image.data=/home/erdouglass/projects/emdb/media-data-dev/images

# --------------------------------------------------------------------
# --- DEVELOPMENT TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=30
tmdb.crew.limit=10
tmdb.rate.limit=39.0

# --------------------------------------------------------------------
# --- PRODUCTION LOGGING CONFIGURATION
# --------------------------------------------------------------------
logging.client.excludes=https://api.themoviedb.org/3/person,http://image.tmdb.org/t/p