# --------------------------------------------------------------------
# --- DEFAULT TMDB CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client.tmdb-movie.url=https://api.themoviedb.org/3
