# --------------------------------------------------------------------
# --- DEFAULT TMDB CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client.tmdb-image.url=http://image.tmdb.org/t/p/original
quarkus.rest-client.tmdb-movie.url=https://api.themoviedb.org/3
quarkus.rest-client.tmdb-person.url=https://api.themoviedb.org/3
quarkus.rest-client.tmdb-series.url=https://api.themoviedb.org/3

