
# --------------------------------------------------------------------
# --- DEFAULT TMDB CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbImageClient".url=http://image.tmdb.org/t/p/original
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbMovieClient".url=https://api.themoviedb.org/3/movie
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbPersonClient".url=https://api.themoviedb.org/3/person
quarkus.rest-client."com.erdouglass.emdb.scraper.client.TmdbSeriesClient".url=https://api.themoviedb.org/3/tv
