# --------------------------------------------------------------------
# --- PRODUCTION CONFIGURATION
# --------------------------------------------------------------------
emdb.image.data=/images

# --------------------------------------------------------------------
# --- PRODUCTION LOGGING CONFIGURATION
# --------------------------------------------------------------------
logging.client.excludes=https://api.themoviedb.org/3/person,http://image.tmdb.org/t/p

# --------------------------------------------------------------------
# --- PRODUCTION TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=10000
tmdb.crew.limit=10000
tmdb.rate.limit=38
