# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
emdb.image.data=/home/erdouglass/projects/emdb/media-data-dev/images

# --------------------------------------------------------------------
# --- PRODUCTION LOGGING CONFIGURATION
# --------------------------------------------------------------------
logging.client.excludes=https://api.themoviedb.org/3/person,http://image.tmdb.org/t/p

# --------------------------------------------------------------------
# --- DEVELOPMENT TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=2
tmdb.crew.limit=0
tmdb.rate.limit=50
