# --------------------------------------------------------------------
# --- PRODUCTION CONFIGURATION
# --------------------------------------------------------------------
emdb.image.data=/images

# --------------------------------------------------------------------
# --- PRODUCTION TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=3
tmdb.crew.limit=1
tmdb.rate.limit=50
