
    create table emdb_notification.Ingest (
        id uuid not null,
        emdb_id bigint,
        last_modified timestamp(6) with time zone,
        message varchar(255),
        name varchar(140),
        source varchar(255) not null check ((source in ('GATEWAY','MEDIA','SCHEDULER','SCRAPER','USER'))),
        status varchar(255) not null check ((status in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        tmdb_id integer not null,
        type varchar(255) not null check ((type in ('MOVIE','PERSON','SERIES'))),
        primary key (id)
    );

    create table emdb_notification.status_events (
        id bigint generated by default as identity,
        created timestamp(6) with time zone not null,
        message varchar(255),
        source varchar(255) not null check ((source in ('GATEWAY','MEDIA','SCHEDULER','SCRAPER','USER'))),
        status varchar(255) not null check ((status in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        correlation_id uuid not null,
        primary key (id),
        constraint uq_status_events_ingest_status unique (correlation_id, status)
    );

    alter table if exists emdb_notification.status_events 
       add constraint FKnkks9jgmwyhgci74x6rduafow 
       foreign key (correlation_id) 
       references emdb_notification.Ingest;
