
    create table emdb_notification.ingest (
        id uuid not null,
        emdb_id bigint,
        last_modified timestamp(6) with time zone not null,
        message varchar(255) not null,
        name varchar(140),
        source varchar(255) not null check ((source in ('GATEWAY','MEDIA','SCHEDULER','SCRAPER'))),
        status varchar(255) not null check ((status in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        tmdb_id integer not null,
        type varchar(255) not null check ((type in ('MOVIE','PERSON','SERIES'))),
        primary key (id)
    );

    create table emdb_notification.ingest_status_change (
        id bigint generated by default as identity,
        last_modified timestamp(6) with time zone not null,
        message varchar(255) not null,
        source varchar(255) not null check ((source in ('GATEWAY','MEDIA','SCHEDULER','SCRAPER'))),
        status varchar(255) not null check ((status in ('SUBMITTED','STARTED','EXTRACTED','COMPLETED','FAILED'))),
        ingest_id uuid not null,
        primary key (id),
        constraint uk_iscn_ingest_status_last_modified unique (ingest_id, status, last_modified)
    );

    create index idx_ingest_last_modified 
       on emdb_notification.ingest (last_modified desc);

    create index idx_ingest_tmdb_id 
       on emdb_notification.ingest (tmdb_id);

    create index idx_iscn_ingest_last_modified 
       on emdb_notification.ingest_status_change (ingest_id, last_modified desc);

    alter table if exists emdb_notification.ingest_status_change 
       add constraint fk_iscn_ingest 
       foreign key (ingest_id) 
       references emdb_notification.ingest;
