package com.erdouglass.emdb.media.adapter.outbound.persistence.movie;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import com.erdouglass.emdb.media.LanguageCode;
import com.erdouglass.emdb.media.Title;

@Entity 
@Table(
  name = "movie",
  uniqueConstraints = {
    @UniqueConstraint(name = "uq_movie_surrogate_id", columnNames = { "surrogate_id" }),
    @UniqueConstraint(name = "uq_movie_tmdb_id", columnNames = { "tmdb_id" }),
  }
)
class MovieEntity {
  
  /// The primary key is generated by a database sequence upon insertion. It is
  /// URL friendly making it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "movie_seq")
  @SequenceGenerator(name = "movie_seq", sequenceName = "movie_seq", initialValue = 1, allocationSize = 1)
  private Long id;
  
  @Column(name = "original_language", length = LanguageCode.LENGTH)
  private String originalLanguage;
  
  @Column(name = "release_date")
  private LocalDate releaseDate;
  
  @Column(name = "score", precision = 5, scale = 3)
  private BigDecimal score;
  
  /// Internal surrogate id, time based UUID7, generated by the application that 
  /// never gets exposed to the public.
  @Column(name = "surrogate_id", nullable = false, updatable = false)
  private UUID surrogateId;
  
  @Column(nullable = false, length = Title.MAX_LENGTH)
  private String title;
  
  @Column(name = "tmdb_id", nullable = false, updatable = false)
  private Integer tmdbId;
  
  @Version
  private long version;
  
  MovieEntity() {}

  public void setId(Long id) { this.id = id; }
  public Long getId() { return id; }
  
  public void setSurrogateId(UUID surrogateId) { this.surrogateId = surrogateId; }
  public UUID getSurrogateId() { return surrogateId; }
  
  public void setTmdbId(int tmdbId) { this.tmdbId = tmdbId; }
  public Integer getTmdbId() { return tmdbId; }
  
  public void setVersion(long version) { this.version = version; }
  public Long getVersion() { return version; }
  
  public void setTitle(String title) { this.title = title; }
  public String getTitle() { return title; }
  
  public void setReleaseDate(LocalDate releaseDate) { this.releaseDate = releaseDate; }
  public Optional<LocalDate> getReleaseDate() { return Optional.ofNullable(releaseDate); }
  
  public void setScore(BigDecimal score) { this.score = score; }
  public Optional<BigDecimal> getScore() { return Optional.ofNullable(score); }
  
  public void setOriginalLanguage(String originalLanguage) { this.originalLanguage = originalLanguage; }
  public Optional<String> getOriginalLanguage() { return Optional.ofNullable(originalLanguage); }
}
