package com.erdouglass.emdb.notification.ingest;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import org.hibernate.annotations.UuidGenerator;

import com.erdouglass.emdb.media.MediaType;

@Entity
@Table(name = "ingest")
class Ingest {
  
  @NotNull
  @Column(name = "correlation_id", nullable = false, updatable = false)
  private UUID correlationId;
  
  @NotNull
  @Column(name = "created_at")
  private Instant createdAt;
  
  /// The primary key is a surrogate key generated by the database using 
  /// [UuidGenerator.Style.TIME] strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private MediaType mediaType;
  
  @NotNull
  private String message;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "event_type", length = 20)
  private Type type;
  
  Ingest() {}
  
  public void setCorrelationId(UUID correlationId) {
    this.correlationId = correlationId;
  }
  
  public UUID getCorrelationId() {
    return correlationId;
  }
  
  public void setCreatedAt(Instant createdAt) {
    this.createdAt = createdAt;
  }
  
  public Instant getCreatedAt() {
    return createdAt;
  }
  
  public UUID getId() {
    return id;
  }  

  public void setMessage(String message) {
    this.message = message;
  }
  
  public String getMessage() {
    return message;
  }
  
  public void setMediaType(MediaType mediaType) {
    this.mediaType = mediaType;
  }
  
  public MediaType getMediaType() {
    return mediaType;
  }
  
  public void setType(Type type) {
    this.type = type;
  }
  
  public Type getType() {
    return type;
  }
  
  @Override
  public String toString() {
    return "Ingest[id=" + id
        + ", createdAt=" + createdAt
        + ", type=" + type
        + ", mediaType=" + mediaType
        + ", message=" + message
        + "]";
  }
  
  public enum Type {
    SUBMITTED("Submitted"),
    STARTED("Started"),
    PROGRESSED("Progressed"),
    COMPLETED("Completed"),
    FAILED("Failed");
    
    private final String type;
    
    Type(String type) {
      this.type = type;
    }
    
    @Override
    public String toString() {
      return type;
    }
  }
}
