package com.erdouglass.emdb.media.domain.shared;

import java.time.Instant;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

@Entity
@Table(name = "credits")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
public abstract class Credit {
  private static final int CREDIT_TYPE_MAX_LENGTH = 4;
  
  /// The timestamp when this credit was first persisted. This is automatically
  /// managed by Hibernate.
  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant createdAt;
  
  /// The primary key is a surrogate key generated by the database using 
  /// [UuidGenerator.Style.TIME] strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  /// The timestamp when this credit was last updated. This is automatically
  /// managed by Hibernate.
  @UpdateTimestamp
  @Column(nullable = false)
  private Instant modifiedAt;
  
  /// Billing/display order. Mapped to `credit_order` because `order` is a
  /// reserved SQL word.
  @PositiveOrZero
  @Column(name = "credit_order")
  private Integer creditOrder;
  
  /// The foreign key in the Credits table that points back to the People table.
  @NotNull
  @Column(name = "person_id", nullable = false, updatable = false)
  private Long personId; 
  
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "credit_type", updatable = false, length = CREDIT_TYPE_MAX_LENGTH)
  private CreditType type; 
  
  protected Credit() {}
  
  public Instant getCreatedAt() {
    return createdAt;
  }
  
  public UUID getId() {
    return id;
  }
  
  public Instant getModifiedAt() {
    return modifiedAt;
  }
  
  public void setOrder(Integer creditOrder) {
    this.creditOrder = creditOrder;
  }
  
  public Integer getOrder() {
    return creditOrder;
  }
  
  public void setPersonId(Long personId) {
    this.personId = personId;
  }
  
  public Long getPersonId() {
    return personId;
  }
  
  public void setType(CreditType type) {
    this.type = type;
  }
  
  public CreditType getType() {
    return type;
  }
  
  public enum CreditType {
    CAST("cast"), 
    CREW("crew");
    
    private static final Map<String, CreditType> CACHE = Stream.of(values())
        .collect(Collectors.toMap(CreditType::name, Function.identity()));
    
    private final String type;
    
    CreditType(String type) {
      this.type = type;
    }
    
    public static CreditType from(String type) {
      return Optional.ofNullable(CACHE.get(type.toUpperCase()))
          .orElseThrow(() -> new IllegalArgumentException("Invalid credit type: " + type));
    }
     
    @Override
    public String toString() {
      return type;
    }
  }
}
