package com.erdouglass.emdb.media.domain.shared;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import com.erdouglass.emdb.media.MediaConstants;
import com.erdouglass.emdb.media.show.ShowConstants;
import com.erdouglass.emdb.media.show.ShowStatus;

@MappedSuperclass
public abstract class Show extends Media<Long> {
  
  @Column(unique = true)
  private UUID backdrop;
  
  @Size(max = MediaConstants.URL_MAX_LENGTH)
  private String homepage;
  
  /// The primary key is generated by a database sequence that is intentionally 
  /// exposed to the public giving it business meaning. This is URL friendly and
  /// makes it easy for users to discover and link to content.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  private Long id;
  
  @NotBlank
  @Column(name = "original_language")
  @Size(min = MediaConstants.ISO_639_1_LENGTH, max = MediaConstants.ISO_639_1_LENGTH)
  private String originalLanguage;
  
  @Size(max = ShowConstants.OVERVIEW_MAX_LENGTH)
  private String overview;
  
  @Column(unique = true)
  private UUID poster;
  
  @NotNull
  @Min(0)
  @Max(10)
  private Float score;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(length = ShowConstants.STATUS_MAX_LENGTH)
  private ShowStatus status;
  
  @Size(max = ShowConstants.TAGLINE_MAX_LENGTH)
  private String tagline;
  
  @NotBlank
  @Size(max = ShowConstants.TITLE_MAX_LENGTH)
  private String title;
  
  protected Show() {}
  
  protected Show(long externalId) {
    super(externalId);
  }
  
  public void setBackdrop(UUID backdrop) {
    this.backdrop = backdrop;
  }

  public UUID getBackdrop() {
    return backdrop;
  }
  
  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public String getHomepage() {
    return homepage;
  }
  
  public Long getId() {
    return id;
  }

  public void setOriginalLanguage(String originalLanguage) {
    this.originalLanguage = originalLanguage;
  }

  public String getOriginalLanguage() {
    return originalLanguage;
  }
  
  public void setOverview(String overview) {
    this.overview = overview;
  }

  public String getOverview() {
    return overview;
  }

  public void setPoster(UUID poster) {
    this.poster = poster;
  }

  public UUID getPoster() {
    return poster;
  }
  
  public void setScore(Float score) {
    this.score = score;
  }

  public Float getScore() {
    return score;
  }

  public void setStatus(ShowStatus status) {
    this.status = status;
  }

  public ShowStatus getStatus() {
    return status;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

  public String getTagline() {
    return tagline;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getTitle() {
    return title;
  }  
}
