# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.status-events-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.status-events-out.exchange.name=emdb.events
mp.messaging.outgoing.status-events-out.exchange.type=direct