# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60314

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.ingest-media-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-media-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-media-out.exchange.type=direct
mp.messaging.outgoing.ingest-media-out.default-routing-key=media.ingest

mp.messaging.incoming.ingest-media-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-media-in.exchange.name=emdb.commands
mp.messaging.incoming.ingest-media-in.exchange.type=direct
mp.messaging.incoming.ingest-media-in.routing-keys=media.ingest
mp.messaging.incoming.ingest-media-in.queue.name=emdb-ingest.ingest-media
mp.messaging.incoming.ingest-media-in.max-outstanding-messages=1

mp.messaging.outgoing.save-movie-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.save-movie-out.exchange.name=emdb.commands
mp.messaging.outgoing.save-movie-out.exchange.type=direct
mp.messaging.outgoing.save-movie-out.default-routing-key=movie.save
mp.messaging.outgoing.save-movie-out.publish-confirms=true

mp.messaging.outgoing.save-series-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.save-series-out.exchange.name=emdb.commands
mp.messaging.outgoing.save-series-out.exchange.type=direct
mp.messaging.outgoing.save-series-out.default-routing-key=series.save
mp.messaging.outgoing.save-series-out.publish-confirms=true

mp.messaging.outgoing.save-person-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.save-person-out.exchange.name=emdb.commands
mp.messaging.outgoing.save-person-out.exchange.type=direct
mp.messaging.outgoing.save-person-out.default-routing-key=person.save
mp.messaging.outgoing.save-person-out.publish-confirms=true

# --------------------------------------------------------------------
# --- DEFAULT TMDB CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client.tmdb-movie.url=https://api.themoviedb.org/3
quarkus.rest-client.tmdb-person.url=https://api.themoviedb.org/3
quarkus.rest-client.tmdb-series.url=https://api.themoviedb.org/3
