# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/api/v1
quarkus.http.port=60310

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.ingest-media.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-media.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-media.exchange.type=direct
mp.messaging.outgoing.ingest-media.default-routing-key=ingest.media
