# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-ingest/api
quarkus.http.port=60310
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.ingest-movie-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-movie-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-movie-out.exchange.type=direct
mp.messaging.outgoing.ingest-movie-out.default-routing-key=ingest.movie

mp.messaging.outgoing.ingest-person-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-person-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-person-out.exchange.type=direct
mp.messaging.outgoing.ingest-person-out.default-routing-key=ingest.person
