# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-ingest/api

# --------------------------------------------------------------------
# --- DEVELOPMENT SCHEDULER CONFIGURATION
# 0 0 8 * * ?  - Run every day at 08:00:00 UTC (01:00:00 MST)
# 0 10 0 * * ? - Run every day at 00:10:00 UTC (17:10:00 MST)
# --------------------------------------------------------------------
emdb.movie.scheduler=off
emdb.series.scheduler=off
emdb.person.scheduler=off

# --------------------------------------------------------------------
# --- DEVELOPMENT TEST CONTAINERS CONFIGURATION
# --------------------------------------------------------------------
quarkus.rabbitmq.devservices.shared=true
quarkus.rabbitmq.devservices.service-name=emdb-rabbitmq
quarkus.rabbitmq.devservices.port=5673

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-ingest-service/logs/emdb-ingest-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.SQL".handlers=LOG_FILE
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.common.messaging".level=INFO
quarkus.log.category."com.erdouglass.common.messaging".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.common.rest".level=INFO
quarkus.log.category."com.erdouglass.common.rest".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.ingest".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.ingest".handlers=LOG_FILE
