create sequence emdb_media.movie_sequence start with 1 increment by 1;
create sequence emdb_media.person_sequence start with 1 increment by 50;
create sequence emdb_media.series_sequence start with 1 increment by 1;
create table emdb_media.credits (credit_order integer, credit_type varchar(4) not null check ((credit_type in ('CAST','CREW'))), createdAt timestamp(6) with time zone not null, modifiedAt timestamp(6) with time zone not null, movie_id bigint, person_id bigint not null, id uuid not null, DTYPE varchar(31) not null check ((DTYPE in ('MovieCredit'))), role varchar(100), tmdb_id varchar(255) unique, primary key (id));
create table emdb_media.movies (original_language varchar(2) not null, release_date date, runtime integer, score float4 not null check ((score>=0) and (score<=10)), tmdb_id integer not null unique, budget bigint, createdAt timestamp(6) with time zone not null, id bigint not null, modifiedAt timestamp(6) with time zone not null, revenue bigint, backdrop uuid unique, poster uuid unique, status varchar(16) not null check ((status in ('CANCELED','ENDED','IN_PRODUCTION','PILOT','PLANNED','POST_PRODUCTION','RELEASED','RETURNING_SERIES','RUMORED'))), title varchar(140) not null, tagline varchar(150), overview varchar(1024), homepage varchar(2048), primary key (id), constraint uq_movies_title_release_date unique (title, release_date));
create table emdb_media.people (birth_date date, death_date date, tmdb_id integer not null unique, createdAt timestamp(6) with time zone not null, id bigint not null, modifiedAt timestamp(6) with time zone not null, gender varchar(10) not null check ((gender in ('UNKNOWN','FEMALE','MALE','NON_BINARY'))), profile uuid unique, name varchar(80) not null, birth_place varchar(120), homepage varchar(2048), biography varchar(3900), primary key (id));
create table emdb_media.series (first_air_date date, original_language varchar(2) not null, score float4 not null check ((score>=0) and (score<=10)), tmdb_id integer not null unique, createdAt timestamp(6) with time zone not null, id bigint not null, modifiedAt timestamp(6) with time zone not null, type varchar(11) check ((type in ('SCRIPTED','REALITY','DOCUMENTARY','NEWS','TALK_SHOW','MINISERIES','VIDEO'))), backdrop uuid unique, poster uuid unique, status varchar(16) not null check ((status in ('CANCELED','ENDED','IN_PRODUCTION','PILOT','PLANNED','POST_PRODUCTION','RELEASED','RETURNING_SERIES','RUMORED'))), title varchar(140) not null, tagline varchar(150), overview varchar(1024), homepage varchar(2048), primary key (id), constraint uq_series_title_first_air_date unique (title, first_air_date));
alter table if exists emdb_media.credits add constraint FKlijvv62n5c5egf9pu6r1wo7eq foreign key (person_id) references emdb_media.people;
alter table if exists emdb_media.credits add constraint FK8v3l3o1prgsruxw644rv8f92s foreign key (movie_id) references emdb_media.movies;
