package com.erdouglass.emdb.audit.entity;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import com.erdouglass.emdb.common.command.AuditMetadata.EventSource;
import com.erdouglass.emdb.common.command.AuditMetadata.EventType;

@Entity
@Table(name = "Job_History")
public class AuditLog {
  private static final String SEQUENCE_GENERATOR = "sequence_generator";
  
  /// The surrogate primary key is generated by the database and has no 
  /// business meaning.
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_GENERATOR)
  @SequenceGenerator(
      name = SEQUENCE_GENERATOR, 
      sequenceName = "job_sequence", 
      initialValue = 1)
  private Long id;
  
  @Positive
  private Long latency;
  
  @NotBlank
  private String message;
  
  @NotNull 
  @Min(0) @Max(100)
  @Column(name = "percent_complete")
  private Integer percentComplete;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private EventSource source;
  
  @NotNull
  @Positive
  @Column(name = "tmdb_id")
  private Integer tmdbId;
  
  @NotNull
  @Enumerated(EnumType.STRING)
  private EventType type;
  
  @NotNull
  private Instant timestamp;
  
  @NotBlank 
  @Column(name = "trace_id")
  private String traceId;
  
  AuditLog() {
    
  }
  
  public AuditLog(String traceId) {
    this.traceId = traceId;
  }
  
  public Long id() {
    return id;
  }
  
  public void latency(Long latency) {
    this.latency = latency;
  }
  
  public Long latency() {
    return latency;
  }
  
  public void message(String message) {
    this.message = message;
  }
  
  public String message() {
    return message;
  }
  
  public void percentComplete(Integer percentComplete) {
    this.percentComplete = percentComplete;
  }
  
  public Integer percentComplete() {
    return percentComplete;
  }
  
  public void source(EventSource source) {
    this.source = source;
  }
  
  public EventSource source() {
    return source;
  }
  
  public void tmdbId(Integer tmdbId) {
    this.tmdbId = tmdbId;
  }
  
  public Integer tmdbId() {
    return tmdbId;
  }
  
  public void type(EventType type) {
    this.type = type;
  }
  
  public EventType type() {
    return type;
  }
  
  public void timestamp(Instant timestamp) {
    this.timestamp = timestamp;
  }
  
  public Instant timestamp() {
    return timestamp;
  }
  
  public String traceId() {
    return traceId;
  }
  
  @Override
  public String toString() {
    return "AuditLog[id=" + id
        + ", traceId=" + traceId
        + ", timestamp=" + timestamp
        + ", tmdbId=" + tmdbId
        + ", source=" + source
        + ", type=" + type
        + ", message=" + message
        + ", percentComplete=" + percentComplete
        + ", latency=" + latency
        + "]";
  }
  
}
