# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-gateway-service/logs/emdb-gateway-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."io.quarkus".handlers=LOG_FILE
quarkus.log.category."io.smallrye".level=WARN
quarkus.log.category."io.smallrye".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.gateway".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.gateway".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=DEBUG
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE

# --------------------------------------------------------------------
# --- DEVELOPMENT EMDB CONFIGURATION
# --------------------------------------------------------------------
media.domain=http://localhost:60312/emdb-media/api
scraper.domain=http://localhost:60316/emdb-scraper/api
