
# --------------------------------------------------------------------
# --- ALL PROFILES
# --------------------------------------------------------------------
quarkus.http.root-path=emdb/api
quarkus.http.port=60310
quarkus.index-dependency.web-services.group-id=com.erdouglass
quarkus.index-dependency.web-services.artifact-id=web-services
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.movie-cron-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.movie-cron-out.exchange.name=emdb-exchange
mp.messaging.outgoing.movie-cron-out.exchange.type=topic
mp.messaging.outgoing.movie-cron-out.routing-key=movie.cron

mp.messaging.outgoing.movie-ingest-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.movie-ingest-out.exchange.name=emdb-exchange
mp.messaging.outgoing.movie-ingest-out.exchange.type=topic
mp.messaging.outgoing.movie-ingest-out.routing-key=movie.ingest

# --------------------------------------------------------------------
# --- DEFAULT REST CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client."com.erdouglass.emdb.gateway.client.JobClient".url=http://emdb-job:60318/api/jobs

media=http://emdb-media:60316/api
quarkus.rest-client."com.erdouglass.emdb.gateway.client.MovieClient".url=${media}/movies
quarkus.rest-client."com.erdouglass.emdb.gateway.client.PersonClient".url=${media}/people
