# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------

# --------------------------------------------------------------------
# --- DEVELOPMENT SECURITY CONFIGURATION
# --------------------------------------------------------------------
quarkus.keycloak.devservices.enabled=false
quarkus.oidc.auth-server-url=http://localhost:8080/realms/projects

# --------------------------------------------------------------------
# --- DEVELOPMENT TEST CONTAINERS CONFIGURATION
# --------------------------------------------------------------------
quarkus.rabbitmq.devservices.shared=true
quarkus.rabbitmq.devservices.service-name=emdb-rabbitmq
quarkus.rabbitmq.devservices.port=5673

# --------------------------------------------------------------------
# --- DEVELOPMENT gRPC CONFIGURATION
# --------------------------------------------------------------------
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.clients.media-service.host=localhost
quarkus.grpc.clients.media-service.port=60316
quarkus.grpc.clients.media-service.plain-text=true 

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-gateway-service/logs/emdb-gateway-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."com.erdouglass.emdb.gateway".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.gateway".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=INFO
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE
