# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=emdb/api
quarkus.http.port=60310
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.limits.max-body-size=10M

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.outgoing.ingest-media-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-media-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-media-out.exchange.type=direct
mp.messaging.outgoing.ingest-media-out.routing-key=ingest.media

mp.messaging.incoming.status-events-in.connector=smallrye-rabbitmq
mp.messaging.incoming.status-events-in.exchange.type=direct
mp.messaging.incoming.status-events-in.exchange.name=emdb.events
mp.messaging.incoming.status-events-in.routing-keys=status.changed
mp.messaging.incoming.status-events-in.queue.name=emdb-gateway.status-events
mp.messaging.incoming.status-events-in.queue.durable=false
mp.messaging.incoming.status-events-in.auto-delete=true
mp.messaging.incoming.status-events-in.exclusive=false

# --------------------------------------------------------------------
# --- DEFAULT gRPC CONFIGURATION
# --------------------------------------------------------------------
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.clients.movie-service.plain-text=true
quarkus.grpc.clients.media-service.compression=gzip
quarkus.grpc.clients.media-service.max-inbound-message-size=10485760
