# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=emdb/api
quarkus.http.port=60310
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# --------------------------------------------------------------------
# --- DEFAULT gRPC CONFIGURATION
# --------------------------------------------------------------------
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.clients.media-service.host=localhost
quarkus.grpc.clients.media-service.port=60316
quarkus.grpc.clients.media-service.plain-text=true 
