# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-gateway-service/logs/emdb-gateway-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."com.erdouglass.emdb.gateway".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.gateway".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=INFO
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE

# --------------------------------------------------------------------
# --- DEVELOPMENT REST ENDPOINT CONFIGURATION
# --------------------------------------------------------------------
quarkus.rest-client."com.erdouglass.emdb.gateway.client.JobClient".url=http://localhost:60318/emdb-job/api/jobs/ingest
quarkus.rest-client."com.erdouglass.emdb.gateway.client.MovieClient".url=http://localhost:60316/emdb-media/api/movies
quarkus.rest-client."com.erdouglass.emdb.gateway.client.PersonClient".url=http://localhost:60316/emdb-media/api/people
quarkus.rest-client."com.erdouglass.emdb.gateway.client.SeriesClient".url=http://localhost:60316/emdb-media/api/series
