
# --------------------------------------------------------------------
# --- ALL PROFILES
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60312

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
%prod.rabbitmq-host=rabbitmq
mp.messaging.incoming.movie-cron-in.connector=smallrye-rabbitmq
mp.messaging.incoming.movie-cron-in.exchange.name=emdb-exchange
mp.messaging.incoming.movie-cron-in.exchange.type=topic
mp.messaging.incoming.movie-cron-in.routing-keys=movie.cron
mp.messaging.incoming.movie-cron-in.queue.name=movie-cron

mp.messaging.outgoing.movie-ingest-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.movie-ingest-out.exchange.name=emdb-exchange
mp.messaging.outgoing.movie-ingest-out.exchange.type=topic
mp.messaging.outgoing.movie-ingest-out.routing-key=movie.ingest
