
# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60312

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------

