
# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60312

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.execute-scheduler-in.connector=smallrye-rabbitmq
mp.messaging.incoming.execute-scheduler-in.exchange.name=emdb.commands
mp.messaging.incoming.execute-scheduler-in.exchange.type=direct
mp.messaging.incoming.execute-scheduler-in.queue.name=execute-scheduler
mp.messaging.incoming.execute-scheduler-in.routing-keys=execute.scheduler

mp.messaging.outgoing.ingest-media-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.ingest-media-out.exchange.name=emdb.commands
mp.messaging.outgoing.ingest-media-out.exchange.type=direct
mp.messaging.outgoing.ingest-media-out.routing-key=ingest.media
