# --------------------------------------------------------------------
# --- DEVELOPMENT Scheduler CONFIGURATION
# 0 0 8 * * ?  - Run every day at 08:00:00 UTC (01:00:00 MST)
# 0 10 0 * * ? - Run every day at 00:10:00 UTC (17:10:00 MST)
# --------------------------------------------------------------------
emdb.movie.scheduler=off
emdb.series.scheduler=off
emdb.person.scheduler=off

# --------------------------------------------------------------------
# --- DEVELOPMENT TEST CONTAINERS CONFIGURATION
# --------------------------------------------------------------------
quarkus.rabbitmq.devservices.enabled=false
rabbitmq-host=localhost
rabbitmq-port=5673

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-scheduler-service/logs/emdb-scheduler-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."com.erdouglass.messaging".level=INFO
quarkus.log.category."com.erdouglass.messaging".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.common.api".level=INFO
quarkus.log.category."com.erdouglass.emdb.common.api".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.scheduler".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.scheduler".handlers=LOG_FILE
