# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb
quarkus.http.port=60310
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173

# --------------------------------------------------------------------
# --- DEFAULT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.datasource.jdbc.additional-jdbc-properties.reWriteBatchedInserts=true
quarkus.hibernate-orm.database.default-schema=emdb_media
quarkus.hibernate-orm.jdbc.statement-batch-size=50
#quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.schemas=emdb_media

quarkus.flyway.baseline-on-migrate=true