# --------------------------------------------------------------------
# --- DEVELOPMENT TMDB CONFIGURATION
# --------------------------------------------------------------------
tmdb.cast.limit=3
tmdb.crew.limit=0
tmdb.rate.limit=50.0

# --------------------------------------------------------------------
# --- DEVELOPMENT DATABASE CONFIGURATION
# --------------------------------------------------------------------
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dev
quarkus.hibernate-orm."ingest".schema-management.strategy=drop-and-create
quarkus.hibernate-orm."media".schema-management.strategy=drop-and-create
quarkus.hibernate-orm."notification".schema-management.strategy=drop-and-create

emdb.image.data=/home/erdouglass/projects/emdb/media-data-dev/images/original
emdb.movie.data=/home/erdouglass/projects/emdb/media-data-dev/movies
emdb.series.data=/home/erdouglass/projects/emdb/media-data-dev/series
emdb.person.data=/home/erdouglass/projects/emdb/media-data-dev/people

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-app/logs/emdb.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.SQL".handlers=LOG_FILE
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.common.graphql".level=INFO
quarkus.log.category."com.erdouglass.common.graphql".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.common.messaging".level=INFO
quarkus.log.category."com.erdouglass.common.messaging".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.common.rest".level=INFO
quarkus.log.category."com.erdouglass.common.rest".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.ingest".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.ingest".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.media".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.media".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.emdb.notification".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.notification".handlers=LOG_FILE
