package com.erdouglass.emdb.media.core.series;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

import org.hibernate.annotations.UuidGenerator;

import com.erdouglass.emdb.media.core.Media;
import com.erdouglass.emdb.media.show.ShowConstants;

@Entity
@Table(name = "Roles")
public class Role extends Media<String> {
  
  @NotNull
  @PositiveOrZero
  @Column(name = "episode_count")
  private Integer episodeCount;
  
  /// The primary key is a surrogate key generated by the database using 
  /// [UuidGenerator.Style.TIME] strategy.
  @Id
  @GeneratedValue
  @UuidGenerator(style = UuidGenerator.Style.TIME)
  private UUID id;
  
  @Size(max = ShowConstants.ROLE_MAX_LENGTH)
  private String role;
  
  /// The @JoinColumn annotation maps the {@link SeriesCredit#id} primary key to the
  /// foreign key in the Roles table. A {@code Role} can't exist without a 
  /// {@link SeriesCredit}.
  @ManyToOne
  @JoinColumn(name = "series_credit_id", updatable = false, nullable = false)
  private SeriesCredit seriesCredit;
  
  Role() {}
  
  Role(String tmdbId) {
    super(tmdbId);
  }
  
  public void setEpisodeCount(Integer episodeCount) {
    this.episodeCount = episodeCount;
  }
  
  public Integer getEpisodeCount() {
    return episodeCount;
  }  
  
  public UUID getId() {
    return id;
  }
 
  public void setRole(String role) {
    this.role = role;
  }
  
  public String getRole() {
    return role;
  }
  
  public void setSeriesCredit(SeriesCredit seriesCredit) {
    this.seriesCredit = seriesCredit;
  }
  
  public SeriesCredit getSeriesCredit() {
    return seriesCredit;
  }
  
  @Override
  public String toString() {
    return "Role[id=" + getId()
      + ", tmdbId=" + getTmdbId()
      + ", role=" + getRole()
      + ", episodeCount=" + getEpisodeCount()
      + "]";
  }
}
