plugins {
  id 'java'
  alias(libs.plugins.quarkus)
}

group = 'com.erdouglass.emdb'
version = '1.0.0-SNAPSHOT'

dependencies {
  implementation enforcedPlatform(libs.quarkus.bom)
  
  implementation project(':common-messaging')
  implementation project(':common-rest')
  implementation project(':emdb-ingest-api')
  implementation project(':emdb-ingest-scraper')
  implementation project(':emdb-media-api')
      
  implementation libs.jakarta.data.api
  implementation libs.quarkus.arc
  implementation libs.quarkus.health
  implementation libs.quarkus.hibernate.validator
  implementation libs.quarkus.logging
  implementation libs.quarkus.messaging
  implementation libs.quarkus.messaging.rabbitmq
  implementation libs.quarkus.prometheus
  implementation libs.quarkus.rest
  implementation libs.quarkus.rest.jackson
  implementation libs.quarkus.rest.client.jackson
  
  testImplementation libs.quarkus.junit
}


