# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILE
# --------------------------------------------------------------------
quarkus.http.root-path=/emdb-job/api
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317

# --------------------------------------------------------------------
# --- DEVELOPMENT LOGGING CONFIGURATION
# --------------------------------------------------------------------
quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] - %s%e%n
quarkus.log.handler.file."LOG_FILE".enabled=true
quarkus.log.handler.file."LOG_FILE".path=/home/erdouglass/projects/emdb/emdb-job-service/logs/emdb-job-service.log
quarkus.log.handler.file."LOG_FILE".format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %l - %s%e%n
quarkus.log.category."com.erdouglass.emdb.job".level=DEBUG
quarkus.log.category."com.erdouglass.emdb.job".handlers=LOG_FILE
quarkus.log.category."com.erdouglass.webservices".level=INFO
quarkus.log.category."com.erdouglass.webservices".handlers=LOG_FILE

# --------------------------------------------------------------------
# --- DEVELOPMENT PROFILES DATABASE
# --------------------------------------------------------------------
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/dev
quarkus.flyway.clean-at-start=true
