
# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60318

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.job-history-in.connector=smallrye-rabbitmq
mp.messaging.incoming.job-history-in.exchange.name=emdb.events
mp.messaging.incoming.job-history-in.exchange.type=topic
mp.messaging.incoming.job-history-in.routing-keys=ingest.status.*
mp.messaging.incoming.job-history-in.queue.name=job-history
mp.messaging.incoming.job-history-in.max-outstanding-messages=1
mp.messaging.incoming.job-history-in.queue.arguments.x-single-active-consumer=true
mp.messaging.incoming.job-history-in.queue.arguments.x-single-active-consumer.type=boolean

# --------------------------------------------------------------------
# --- DEFAULT PROFILES DATABASE
# --------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/prod
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.hibernate-orm.database.default-schema=emdb_job
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.flyway.schemas=emdb_job
