
# --------------------------------------------------------------------
# --- DEFAULT CONFIGURATION
# --------------------------------------------------------------------
quarkus.http.root-path=api
quarkus.http.port=60318

# --------------------------------------------------------------------
# --- DEFAULT MESSAGING CONFIGURATION
# --------------------------------------------------------------------
mp.messaging.incoming.ingest-status-in.connector=smallrye-rabbitmq
mp.messaging.incoming.ingest-status-in.exchange.name=emdb-events
mp.messaging.incoming.ingest-status-in.exchange.type=topic
mp.messaging.incoming.ingest-status-in.routing-keys=ingest.status.*
mp.messaging.incoming.ingest-status-in.queue.name=ingest-status

# --------------------------------------------------------------------
# --- DEFAULT PROFILES DATABASE
# --------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/prod
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.hibernate-orm.database.default-schema=emdb_job
quarkus.hibernate-orm.jdbc.statement-batch-size=50
quarkus.flyway.schemas=emdb_job
