package com.erdouglass.emdb.media.person.domain;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.erdouglass.emdb.media.kernel.SourceId;
import com.erdouglass.emdb.media.kernel.Version;
import com.erdouglass.emdb.media.person.domain.exception.StalePersonException;

public class Person {
  private final PersonId id;
  private final PersonPublicId publicId;
  private final SourceId sourceId;
  private final Version version;
  
  private PersonDetails details;
  
  private Person(
      PersonId id, 
      PersonPublicId publicId, 
      SourceId sourceId, 
      PersonDetails details, 
      Version version) {
    this.id = Objects.requireNonNull(id, "id is required");
    this.publicId = publicId;
    this.sourceId = Objects.requireNonNull(sourceId, "sourceId is required");
    this.details = Objects.requireNonNull(details, "details are required");
    this.version = version;
  }
  
  /// Creates a new, unpersisted person aggregate.
  ///
  /// The public id and version stay absent until the person is written, because
  /// both are derived from database-assigned values. The person starts unlocked.
  ///
  /// @param id the surrogate id, generated by the caller; must not be `null`
  /// @param sourceId the natural id from the upstream catalogue
  /// @param details the initial details; must carry at least a name
  /// @return an aggregate that reports empty from [#publicId()] and [#version()]
  /// @throws NullPointerException if `id`, `tmdbId` or `details` is `null`
  public static Person create(PersonId id, SourceId sourceId, PersonDetails details) {
    return new Person(id, null, sourceId, details, null);
  }
  
  /// Reconstructs a persisted person from stored state.
  ///
  /// This bypasses every domain rule by design — it restores state that was
  /// already validated when it was written, and a lock must not prevent a locked
  /// person from being loaded. Only the persistence adapter should call it;
  /// application code creates person with [#create(PersonId, TmdbId, PersonDetails)].
  ///
  /// @param id the stored surrogate id
  /// @param publicId the stored public id
  /// @param sourceId the stored natural id
  /// @param locked whether the stored person is locked against detail changes
  /// @param details the stored details
  /// @param version the stored optimistic-locking version
  /// @return the rehydrated aggregate
  /// @throws NullPointerException if `id`, `tmdbId` or `details` is `null`
  public static Person rehydrate(
      PersonId id, 
      PersonPublicId publicId, 
      SourceId sourceId, 
      PersonDetails details, 
      Version version) {
    return new Person(id, publicId, sourceId, details, version);
  }
  
  /// Replaces the details wholesale and reports what moved.
  ///
  /// Replacement, not merge: any field absent from `targetDetails` is treated as
  /// cleared and appears in the returned list as a removal. The aggregate is
  /// mutated even when nothing differs, in which case the returned list is
  /// empty and the caller can skip persisting.
  ///
  /// The returned changes are the caller's to audit — this method records
  /// nothing itself.
  ///
  /// @param targetDetails the complete intended details
  /// @return the field-level differences in declaration order, empty when the
  ///         details already matched; never `null`
  /// @throws NullPointerException if `targetDetails` is `null`
  /// @throws LockedPersonException if the movie is locked, including when the
  ///         incoming details are identical to the current ones
  public List<PersonFieldChange> update(PersonDetails targetDetails) {
    Objects.requireNonNull(targetDetails, "details are required");
    var changes = PersonField.diff(this.details, targetDetails);
    if (changes.isEmpty()) {
      return changes;
    }
    this.details = targetDetails;
    return changes;
  }
  
  /// Renders the current details as if every populated field had just been added.
  ///
  /// Used to seed the audit trail on insert, so that a title's history starts
  /// with a complete picture rather than with nothing.
  ///
  /// @return one addition per populated field, in declaration order
  public List<PersonFieldChange> changesAsAdded() { return PersonField.diff(null, details); }  
  
  /// Renders the current details as if every populated field had just been
  /// removed.
  ///
  /// Used to close out the audit trail before a delete, so the history records
  /// what was lost rather than ending abruptly.
  ///
  /// @return one removal per populated field, in declaration order
  public List<PersonFieldChange> changesAsDeleted() { return PersonField.diff(details, null); }
  
  /// Asserts that the caller's view of this person is current.
  ///
  /// Call before mutating on behalf of a client that read the person earlier; a
  /// mismatch means someone else wrote in between and the caller's edit would
  /// silently discard that write.
  ///
  /// An unpersisted person has no version and therefore never matches.
  ///
  /// @param expected the version the caller believes it holds
  /// @throws StalePersonException if this person has no version, or its version
  ///         differs from `expected`
  /// @throws NullPointerException if `expected` is `null`
  public void checkVersion(Version expected) {
    Objects.requireNonNull(expected, "expected version is required");
    if (version == null || !version.equals(expected)) {
      throw new StalePersonException("person %s has invalid version: %d"
          .formatted(publicId.value(), version.value()));
    }
  }
  
  /// Getters
  public PersonDetails details() { return details; }  
  public PersonId id() { return id; }  
  public Optional<PersonPublicId> publicId() { return Optional.ofNullable(publicId); }
  public SourceId sourceId() { return sourceId; }
  public Optional<Version> version() { return Optional.ofNullable(version); }
  
  /// Compares by surrogate id only.
  ///
  /// Two instances describing the same person are equal even if their details,
  /// lock state or version differ — identity is the aggregate's, not the
  /// snapshot's. Use [#details()] to compare content.
  ///
  /// @param obj the object to compare with
  /// @return `true` if `obj` is a movie with the same [#id()]
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Person other = (Person) obj;
    return Objects.equals(id, other.id);
  }
  
  @Override
  public String toString() {
    return getClass().getSimpleName() + "[id=" + id.value()
        + ", publicId=" + publicId().map(PersonPublicId::value).orElse(null)
        + ", source=" + sourceId().provider()
        + ", sourceId=" + sourceId().id()
        + ", version=" + version().map(Version::value).orElse(null)
        + ", name=" + details.name().value()
        + ", birthDate=" + details.birthDate().map(BirthDate::toLocalDate).orElse(null)
        + ", deathDate=" + details.deathDate().map(DeathDate::toLocalDate).orElse(null)
        + ", gender=" + details.gender()
        + "]";
  }  
}
